Fix handling of err codes in thermal solver
MALI-Dev/E3SM pull request #101
Opened 2024-01-30 04:23 UTC by matthewhoffman

As written, some errors were not being handled properly, leading to runs being aborted without useful information written to an err log file. This PR writes all error related messages to the err log, sets the err code to 1, and returns control to the calling routine.

2024-02-14 16:38 UTC, matthewhoffman commented
# Testing

compass full_integration suite on Chicoma

Baseline comparison fails on the 4 EISMINT2  and two Humboldt "full-physics" tests, all of which use the thermal solver.  The enthalpy benchmark test is unaffected.
```
Test Runtimes:
00:08 PASS landice_dome_2000m_sia_restart_test
00:03 PASS landice_dome_2000m_sia_decomposition_test
00:04 PASS landice_dome_variable_resolution_sia_restart_test
00:02 PASS landice_dome_variable_resolution_sia_decomposition_test
00:21 PASS landice_enthalpy_benchmark_A
00:14 FAIL landice_eismint2_decomposition_test
00:13 FAIL landice_eismint2_enthalpy_decomposition_test
00:14 FAIL landice_eismint2_restart_test
00:13 FAIL landice_eismint2_enthalpy_restart_test
00:08 PASS landice_greenland_sia_restart_test
00:07 PASS landice_greenland_sia_decomposition_test
00:06 PASS landice_hydro_radial_restart_test
00:04 PASS landice_hydro_radial_decomposition_test
00:29 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-none_subglacialhydro
00:30 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-none_subglacialhydro
00:18 PASS landice_dome_2000m_fo_decomposition_test
00:18 PASS landice_dome_2000m_fo_restart_test
00:11 PASS landice_dome_variable_resolution_fo_decomposition_test
00:27 PASS landice_dome_variable_resolution_fo_restart_test
00:16 PASS landice_circular_shelf_decomposition_test
00:50 PASS landice_greenland_fo_decomposition_test
00:47 PASS landice_greenland_fo_restart_test
00:25 PASS landice_thwaites_fo_decomposition_test
00:32 PASS landice_thwaites_fo_restart_test
00:14 PASS landice_thwaites_fo-depthInt_decomposition_test
00:22 PASS landice_thwaites_fo-depthInt_restart_test
00:37 FAIL landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
00:25 FAIL landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 08:37
FAIL: 6 tests failed, see above.
```

Details of failing tests:
```
landice/eismint2/decomposition_test
  * step: setup_mesh
  * step: 1proc_run
  * step: 4proc_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_eismint2_decomposition_test.log
  test runtime:        00:14
landice/eismint2/enthalpy_decomposition_test
  * step: setup_mesh
  * step: 1proc_run
  * step: 4proc_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_eismint2_enthalpy_decomposition_test.log
  test runtime:        00:13
landice/eismint2/restart_test
  * step: setup_mesh
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_eismint2_restart_test.log
  test runtime:        00:14
landice/eismint2/enthalpy_restart_test
  * step: setup_mesh
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_eismint2_enthalpy_restart_test.log
  test runtime:        00:13
landice/humboldt/mesh-3km_restart_test/velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting.log
  test runtime:        00:37
landice/humboldt/mesh-3km_restart_test/velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting.log
  test runtime:        00:25
```

I will look into these changes to see if they are expected based on the changes.

2024-02-28 23:20 UTC, matthewhoffman commented
For eismint test with temperature (specifically, using landice/eismint2/decomposition_test), the following differences are reported:
`thickness`:
```
5:  l1: 1.32348898008484e-23  l2: 9.35848032643661e-24  linf: 6.61744490042422e-24
6:  l1: 8.13548676058154e-20  l2: 3.32142078272196e-20  linf: 1.36981109438781e-20
7:  l1: 8.86811732039730e-18  l2: 3.62039459340322e-18  linf: 1.47929010282043e-18
8:  l1: 1.14041006337302e-13  l2: 8.03888639145504e-14  linf: 5.68434188608080e-14
9:  l1: 1.54223969664767e-12  l2: 4.63554077161985e-13  linf: 1.70530256582424e-13
10:  l1: 2.21565062592132e-11  l2: 5.61284619834754e-12  linf: 1.81898940354586e-12
11:  l1: 2.13242068480054e-10  l2: 5.38854151989974e-11  linf: 1.72235559148248e-11
12:  l1: 1.61172242677085e-09  l2: 4.07032982584104e-10  linf: 1.29887212096946e-10
13:  l1: 9.96637453812353e-09  l2: 2.51519280180379e-09  linf: 8.01946953288279e-10
14:  l1: 5.21668929196286e-08  l2: 1.31637221346652e-08  linf: 4.19720436184434e-09
15:  l1: 2.37813246160021e-07  l2: 5.99997907280388e-08  linf: 1.91319600162387e-08
...
30:  l1: 3.73601793556103e-01  l2: 8.51606025133017e-02  linf: 2.84289348380753e-02
```

`temperature`:
```
3:  l1: 2.97961984655350e+00  l2: 9.74713722932335e-01  linf: 5.83515554991521e-01
4:  l1: 4.59444489521574e+01  l2: 8.58622761343868e+00  linf: 2.95839113947792e+00
5:  l1: 1.15587156258964e+02  l2: 2.12406945040075e+01  linf: 7.17296231381602e+00
6:  l1: 1.92490011198170e+02  l2: 3.47385334906336e+01  linf: 1.15195869393879e+01
...
30:  l1: 8.51147001263554e+02  l2: 1.32643312061786e+02  linf: 3.36515248211191e+01
```

`basalTemperature`:
```
2:  l1: 1.99999999999818e-02  l2: 1.41421356237181e-02  linf: 9.99999999999091e-03
3:  l1: 8.50100000000002e+01  l2: 6.00828665261572e+01  linf: 4.24850000000002e+01
4:  l1: 2.54909999999996e+02  l2: 1.04066571722142e+02  linf: 4.24849999999995e+01
5:  l1: 2.54909999999892e+02  l2: 1.04066571722094e+02  linf: 4.24849999999799e+01
6:  l1: 2.54909999998989e+02  l2: 1.04066571721601e+02  linf: 4.24849999997785e+01
...
30:  l1: 2.55073395658192e+02  l2: 1.04044915243464e+02  linf: 4.24761440737743e+01
```

Looking at map view changes, the larger temperature differences are likely coming from slightly differing ice extent in the two version of the code.  There clearly are no major issues going on, but a closer evaluation may be needed.
<img width="1278" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/4182034/686fdb8c-d822-4a42-8636-9a902d7054f9">

2024-02-29 00:05 UTC, matthewhoffman commented
Running the full EISMINT2 exp A, I get these statistics for this branch:
```
MALI volume = 2.0930678718459013
MALI area = 1.024616305852464
MALI melt fraction = 0.5615425250924457
MALI divide thickness = 3671.649439692628
MALI divide basal temperature = 255.16051220241934
```
which has some notable differences compared to the results in the GMD paper, especially melt fraction:
<img width="818" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/4182034/4b768c50-0007-42bf-8285-bfd09b65478e">

Comparing the map view plot from the paper suggests something is not right with the current MALI solution.  I will run again on develop to determine if those issues are from this PR or have crept into the code in the last 5 years.
<img width="1563" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/4182034/2b0f5a53-9ec1-40b2-b498-94baca719f85">

2024-03-15 17:20 UTC, trhille commented
Looking into the two `humboldt` full-physics restart tests that fail. They both pass validation, but fail baseline comparison.
At time zero, the runs are identical, as expected (color is temperature difference, baseline minus comparison run). Contour on let is baseline thickness==1, right is comparison thickness==1.
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/7183378c-5375-48e9-a221-6bd4771a337e)

At time 1, there is a difference in ice extent, with the baseline run advancing one cell in a few places:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/948952b5-7f20-4c60-8c62-eb41decf6102)

At time 2, the ice extents are back to being the same, but with small temperature differences (<< 1K) in the regions upstream of the former mismatched extents:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/3bc3aebc-b9fe-4f63-83be-8edfcc71ebd6)

This persists until the end of the run, with the temperature difference evolving slightly:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/86f2dc86-d2ac-4ccb-824f-a5650960c958)

The thickness differences reflect the temperature differences, with differences of tens of meters at time 1, but only ~1e-2 m in subsequent times.:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/2366010a-7d2b-4ee9-8701-fd0e04c60ebd)

![image](https://github.com/MALI-Dev/E3SM/assets/17446278/b3e78d5f-dbff-44d5-adc0-a98a01ece894)

2024-03-15 17:22 UTC, trhille requested changes
@matthewhoffman, this just needs one or two tiny changes. Based on my investigation of the differences in the `humboldt` runs that failed baseline comparison, I think we can bless these changes.

2024-03-17 21:58 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_thermal.F
> +        maxtempThreshold =  0.1_RKIND + kelvin_to_celsius,   &
I chose this because there are some places in the thermal solver where small thresholds are tolerated, e.g., https://github.com/MALI-Dev/E3SM/blob/fd298b1420ee9e8a3015e484592d8e95aa9ac158/components/mpas-albany-landice/src/mode_forward/mpas_li_thermal.F#L2927-L2937
and I didn't want to think about exactly how small we could get away with without causing potential issues.

However, now that I'm thinking about this more, we never tolerate a temperature *above* freezing so making this smaller is probably a good idea.

2024-03-17 22:06 UTC, matthewhoffman commented
> However, it makes me a little uncomfortable that I don't fully understand where the differences are coming from, or why they show up in the humboldt restart tests but not the decomp tests.

What decomp tests are you referring to?  There are not decomp tests that correspond to the settings in the humboldt restart tests that fail baseline comparison.

As to where the differences are coming from, I think it's that we no longer allow freeze-on in excess of available basal water.  Because we generally (really, always) run with no basal water that means any freeze-on gets zeroed out.  I think freeze-on is generally quit rare and occurs in thin ice where the cold surface can be felt at the bottom of the ice in the conductive flux.  I think it often shows up in cells with ice that is thinner than we really mean ice to be (say, <10 m).  I haven't confirmed these ideas, but I can take a closer look if you don't feel entirely comfortable.

2024-03-19 21:12 UTC, matthewhoffman commented
@trhille , I did a little more investigation and I think the differences you showed above are demonstrating exactly what this PR is meant to fix.  Thanks for identifying those differences in the Humboldt case.  I reran the baseline with BMB fields in the output.  The stray advancing cell on the upper left of the plots you show above has ice thickness of 0.0283 m at time 0 and thickness of 66.8989 m at time 1.  The groundedBasalMassBalApplied value at time 1 is 0.00329 kg/m2/s.  This is a really huge basal mass balance value, and we should not be having positive BMB at all when we have no basal water enabled in the model.  That value is equivalent to a 56.9 m ice equivalent for the 6-month time interval being used in this test, which goes a long way to explaining the different in ice thickness (the rest presumably coming from flux divergence or possibly SMB).  The crazy positive BMB values Holly was seeing in ISMIP6 runs seemed to occur when ice thickness was very small, so this result is consistent.  If we were able to use a nonzero thermal thickness limit, we might not see these issues, but because we need to have realistic ice temperatures calculated for any nonzero ice thickness, they show up when ice thickness is small.  

Based on this additional investigation, and rerunning compass tests with the additional commit I pushed today with code review updates, I am going to merge this PR.

![image](https://github.com/MALI-Dev/E3SM/assets/4182034/c38f6763-242b-4b1d-9780-797860ea9f60)

2024-03-19 21:15 UTC, merged