Add subglacial hydrology quantities to the regional stats analysis member
MALI-Dev/E3SM pull request #105
Opened 2024-02-22 16:24 UTC by andrewdnolan

- This PR follows #82, which added subglacial hydrology (SGH) quantities to the global stats analysis member by adding SGH quantities to the regional stats analysis member. 

- This PR also address a [bug](https://github.com/MALI-Dev/E3SM/blob/8be18efd4a8bff2008d38388de7fa1d28709a4a8/components/mpas-albany-landice/src/analysis_members/mpas_li_global_stats.F#L464-L470) introduced in #82 where the calculation of `groundingLineFlux` and `groundingLineMigrationFlux` were moved with a `if config_SGH then` condition. The bug prevents `groundingLineFlux` and `groundingLineMigrationFlux` from being calculated by global stats unless the SGH model is turned on, despite these quantities apply to simulation where SGH is not used.

2024-02-22 19:26 UTC, andrewdnolan commented
The code changes committed above compile on `chicoma` without any problems (e.g. `make gnu-cray ALBANY=true DEBUG=true`). But before I go ahead and test the regional stats, I have two implementation questions: 

### (1) How to determine upwind cell for SGH quantities?  

Currently `groundingLineFlux` is the only edge quantity calculated by regional stats. The edge values (of `groundingLineFlux`) are assigned to the region  corresponding to the upwind cell of an edge, where the upwind cell is determined by surface velocity. 

Assigning the SGH edge quantities to the region corresponding to the upwind cell seems like a fine choice to me, but is using velocity to determine the upwind cell for SGH quantities appropriate? Should we be using the hydraulic potential? 

(As far as I can tell, the need to determine upwind cells (of edges) is because the `regionMask` is defined at cell centers, so there's ambiguity as to which region an edge quantity applies to).

2024-02-22 19:26 UTC, andrewdnolan commented on components/mpas-albany-landice/src/analysis_members/mpas_li_regional_stats.F
> +      real (kind=RKIND), dimension(:), allocatable:: regionalSumFlotationFraction
### (2) Should there be a `regionalSumFloatingArea`? 

I don't think by any means this is necessary but I'm wondering if it might be useful in relation to calculating `regionalAvgFlotationFraction`, which I've included following #82. 

Just looking around all of the other average quantities (in either regional or global) are calculated from a corresponding sum value included in the streams (e.g. `regionalSumGroundedBasalMassBal` and `regionalAvgGroundedBasalMelt`). Given the way averages are calculated (via reductions of the sums across the number of tasks) this seems like an efficient/useful pairing of variables. 

Since there is no `regionalSumFloatingArea` in the streams, I need to allocate a scratch array to store the `regionalSumFloationFraction` before I can divide by area to get the average floatation fraction. Since I need allocate this scratch array anyway, does it make sense to include some type of analogous sum value in the streams (e.g. `regionalSumFloatingArea`)?

2024-02-22 19:39 UTC, matthewhoffman commented on components/mpas-albany-landice/src/analysis_members/mpas_li_regional_stats.F
> +      real (kind=RKIND), dimension(:), allocatable:: regionalSumFlotationFraction
Couple questions - do you mean regional**Grounded**IceArea?  The flotation fraction only get calculated on the grounded portion of the domain, not the floating portion.  Regardless, I'm confused because `regionalGroundedIceArea` and `regionalFloatingIceArea` do exist in regional stats already.  Or is what you need not exactly that?

2024-02-22 19:58 UTC, matthewhoffman commented
Regarding edge masks, I think what we should be doing is generating edge region masks in addition to cell region masks for our meshes when we call this tool: https://github.com/MPAS-Dev/MPAS-Tools/blob/master/conda_package/mpas_tools/mesh/mask.py#L38-L42

GL flux was the first edge quantity in regional stats so I think when that got implemented either we forgot that edge masks could be generated or we decided that doing it based on upstream cell was a better approach.  Now that we have more edge fields with hydrology, this probably requires more careful consideration.

Adopting edge region masks will make implementation in regional stats easy, but it will require any existing meshes to have the masks regenerated to include edge masks to work with new versions of the code.  We could also make a namelist option to select whether to use edge masks or some sort of 'uphill' cell (details would need to be sorted out related to your original question).

Whether it is better to base it off of an 'uphill' cell is a question I need to think about a bit more first.  In practice, it shouldn't really matter because region boundaries should not be cutting through areas of interest.

I think the cleaner implementation is to start requiring an edge mask and to make all the new hydrology edge fields plus the existing GL flux fields use that going forward, even if that requires some extra steps to update mask files for meshes we currently use.  @trhille , what do you think?

(BTW, I think there is a historical reason `blockSumRegionGLflux` used the upglacier cell related to not having `fluxAcrossGroundingLine` on edges available in an earlier version of the code and essentially calculating that in regional/global stats.  When we were finding the upglacier cell anyway, it probably seemed simplest to just use that to assign the region.  Now that we actually have edge fields available work with, it would seem less complicated to assign the regions based on the edge mask.  That would avoid a given edge potentially changing regions as a simulation progresses.)

2024-02-22 22:31 UTC, andrewdnolan commented on components/mpas-albany-landice/src/analysis_members/mpas_li_regional_stats.F
> +      real (kind=RKIND), dimension(:), allocatable:: regionalSumFlotationFraction
Per some discussion in person the numerator needed for calculating `regionalAvgFlotationFraction` doesn't really have any physical meaning and therefore is not needed in the var struct. 

There's no problem with allocating a local variable, as long as its deallocated (which it is as of [72079b2](https://github.com/MALI-Dev/E3SM/pull/105/commits/72079b26ed186b28a751222b8f0f10e53242d1c3)).

2024-03-05 17:06 UTC, matthewhoffman requested changes
@andrewdnolan , this looks great!  I have requested a few small changes, but this is close to ready, pending the conclusion of our investigation into the global/regional differences.

2024-03-05 17:06 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="regionVertexMasks"/>
These will also have to be added to the restart stream.  That's a bit unfortunate as it will make the files bigger somewhat unnecessarily, but I think that's ok.  @trhille , do you have concerns about that?

2024-03-05 17:06 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="regionVertexMasks"/>
Actually, let's do this - leave regionVertexMasks out of Registry entirely.  But we will generate it in new meshes with the separate compass PR that adds the edge mask.  I.e. going forward, let's have all 3 region masks generated in all new meshes, but we won't actually add the vertex mask to the code until we need it.

2024-03-05 18:27 UTC, andrewdnolan commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="regionVertexMasks"/>
That works for me! I've removed `regionVertexMasks` for now and added `regionEdgeMasks` to the restart stream as of [07db62e](https://github.com/MALI-Dev/E3SM/pull/105/commits/07db62e8c6b1195a134513f23b4131e303e0f916).

2024-03-05 20:48 UTC, matthewhoffman commented on components/mpas-albany-landice/src/analysis_members/mpas_li_regional_stats.F
> +                     (real(regionCellMasks(iRegion,iCell),RKIND) * &
nevermind - as you pointed out, this is handled by the if-statement, which I just flat out missed :)

2024-03-05 21:30 UTC, andrewdnolan commented
### `Global` v.s. `Regional` Budgets

As a first pass at the validating the implementation of the SGH regional statistics, I've compared the regional values summed over the regions to the corresponding value in global stats.  To do this comparison I've used the "relative error" as defined by: `relative_error = (regional_sum - global_val) / global_val`. For an ismip6 like experiment, with SGH turned on, the relative errors over a 65 timestep simulation are: 
```
*****************************************************************************
Var:                                    |Mean|        |Max|         |std|
*****************************************************************************
Subglacial Water Volume............  9.104454e-07  3.238592e-06  7.709992e-07
Subglacial Lake Volume.............  1.211057e-16  5.028270e-16  1.181020e-16
Subglacial Lake Area...............  1.249508e-16  4.362949e-16  1.239689e-16
Basal Melt Input...................  2.569330e-06  2.569330e-06  4.235165e-22
Channel Melt.......................  3.825636e-08  3.899044e-07  8.050388e-08
Dist Water Flux Marine Margin......  1.409128e-16  4.222888e-16  1.173458e-16
Dist Water Flux Terrestrial Margin.  1.211111e-16  6.299816e-16  1.187916e-16
Chnl Water Flux Marine Margin......  1.238991e-16  5.758323e-16  1.287534e-16
Chnl Water Flux Terrestrial Margin.  1.208229e-16  4.068573e-16  1.095703e-16
```

The relative error between global and region stats for most SGH variables achieves double precision roundoff error (~1e-16), except for Subglacial Water Volume, Basal Melt Input, and Channel Melt. Of the SGH quantities the three which are not achieving double precision roundoff error are the most likely to have nonzero values along/near region boundaries. 

As a sanity check, we've looked into overlap/underlap between the region definitions as a possible explanation to the loss of precision between global and regional stats. Plotted below in red are the cell (left) and edge(s) (right) that do not belong to __any__ region (i.e. the underlap).  
![image](https://github.com/MALI-Dev/E3SM/assets/32367657/03016dbc-bf99-4271-9238-c014cf6c0b3a)

By using the residual values from these excluded cell/edges, we can close the budget between regional and global stats $^1$: 
```
*****************************************************************************
Var:                                    |Mean|        |Max|         |std|
*****************************************************************************
Subglacial Water Volume............  2.761222e-16  8.813276e-16  1.995117e-16
Channel Melt.......................  1.702097e-16  5.419756e-16  1.435017e-16
```
and achieve double precision round off error like the other fields above. 

$^1$ : We are unable to do the residual calculation for Basal Melt Input, because the necessary field was not included in the output stream of the testing simulation. But from what we have we can confirm the excluded cell/edges do close the budget for values defined at cells (Subglacial Water Volume)  and at edges (Channel Melt). Plus,  Basal Melt Input is effectively prescribed to the SGH model, so it's a little less important than a prognostic variable (e.g. Channel Melt).

2024-03-05 22:22 UTC, andrewdnolan commented
## Regional SGH edge statistics 

Based on some in person discussion @matthewhoffman, @trhille, and I decided the best solution to the upwind cell problem (described [above](https://github.com/MALI-Dev/E3SM/pull/105#issuecomment-1960107902)) is to require the `regionEdgeMask`, but only for the SGH regional stats. 

Eventually, the `regionEdgeMask` may be needed for non SGH stats, but only using `regionEdgeMask` within a SGH condition seemed like a reasonable stopgap for now.

2024-03-05 22:30 UTC, andrewdnolan commented
# Testing 

Results from a compass baseline comparison, using the full integration suite, on Perlmutter. The `MALI-Dev/develop` branch used to create the baseline was at commit `f79661cb42`. 

```Test Runtimes:
00:35 PASS landice_dome_2000m_sia_restart_test
00:17 PASS landice_dome_2000m_sia_decomposition_test
00:28 PASS landice_dome_variable_resolution_sia_restart_test
00:19 PASS landice_dome_variable_resolution_sia_decomposition_test
00:36 PASS landice_enthalpy_benchmark_A
00:25 PASS landice_eismint2_decomposition_test
00:31 PASS landice_eismint2_enthalpy_decomposition_test
00:27 PASS landice_eismint2_restart_test
00:34 PASS landice_eismint2_enthalpy_restart_test
00:20 PASS landice_greenland_sia_restart_test
00:19 PASS landice_greenland_sia_decomposition_test
00:17 PASS landice_hydro_radial_restart_test
00:07 PASS landice_hydro_radial_decomposition_test
00:27 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-none_subglacialhydro
00:29 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-none_subglacialhydro
00:16 PASS landice_dome_2000m_fo_decomposition_test
00:14 PASS landice_dome_2000m_fo_restart_test
00:13 PASS landice_dome_variable_resolution_fo_decomposition_test
00:10 PASS landice_dome_variable_resolution_fo_restart_test
00:13 PASS landice_circular_shelf_decomposition_test
00:43 PASS landice_greenland_fo_decomposition_test
00:36 PASS landice_greenland_fo_restart_test
00:20 PASS landice_thwaites_fo_decomposition_test
00:31 PASS landice_thwaites_fo_restart_test
00:12 PASS landice_thwaites_fo-depthInt_decomposition_test
00:17 PASS landice_thwaites_fo-depthInt_restart_test
00:31 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
00:18 PASS landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 11:03
PASS: All passed successfully!
```

P.S. Thanks for showing me how to do that today, @trhille!

2024-03-05 22:45 UTC, matthewhoffman requested changes
One small typo to fix

2024-03-05 22:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                            <var name="nVertice<gion"/>
Looks like something got garbled here.  I don't think this field is actually used, which is why this didn't cause any errors.

2024-03-05 22:52 UTC, andrewdnolan commented on components/mpas-albany-landice/src/Registry.xml
> +                            <var name="nVertice<gion"/>
Whoops, I seem to be real sloppy with the vim commands today. Thanks for catching this!

2024-03-05 23:48 UTC, merged

2024-03-05 23:50 UTC, matthewhoffman commented
@andrewdnolan , all look good.  Thanks for implementing this new analysis!