Allow for interior no-flow ice boundaries
MALI-Dev/E3SM pull request #108
Opened 2024-03-20 00:12 UTC by alexolinhager

This PR adds two minor changes that allow for masking out of interior regions of a glacier/ice sheet. Originally designed to run on a configuration where all cells within regions of frozen ice are neglected by setting `thickness` to zero, and frozen regions are surrounded by no flux conditions (`waterFluxMask` =2). Originally, domain boundaries were defined by any cell with a neighbor ID of `nCells +1`, and hydropotential gradients were set to zero along connecting edge. Now, the model relies on `waterFluxMask` to define where gradients should be set to zero, allowing for the creation of no-flow conditions along interior boundaries if desired. Additionally logic was then also added to the definitions of `hydroMarineMarginMask` and `hydroTerrestrialMarginMask` so that they do not include interior boundaries in their masks. Changes made in this PR should not affect model performance for simulations run in typical configurations, as long as `waterFluxMask` is properly implemented along domain boundaries, which is already best practice.

2024-03-20 00:15 UTC, alexolinhager commented
The PR has been successfully run on a version of the AIS hydro mesh where frozen basal ice is masked off, but still needs to be run with the compass integration test suite. I'm happy to do this when I have time tomorrow

2024-03-20 19:14 UTC, matthewhoffman requested changes
@alexolinhager , these changes look good.  I made some suggestions for changes to comments that you can commit directly on Github.  If the full_integration results don't change, I'll go ahead and get this merged.

2024-03-22 00:25 UTC, alexolinhager commented
Currently the humboldt hydro test cases fail the integration test because there is no waterFluxMask  set up for that domain (defaults to zero), so the boundary edges have now have non-zero hydropotential gradients. I think we should be able to change the logic at lines 914 and 964 to zero out gradients at edges are either on domain boundaries or have waterFluxMask = 2, instead of exclusively relying on one or the other. I don't think this will cause unintended ill-effects, but what do you think @matthewhoffman? I can implement it tomorrow and run the test again to try to get this merged before you go out of town

2024-03-22 16:35 UTC, alexolinhager commented
@matthewhoffman All tests now pass with the new commit! If you're happy with the changes I think we can get it merged.

2024-03-25 23:59 UTC, alexolinhager commented
@trhille, and I have been working on this PR so that we can mask of parts of the AIS hydro domain that have a frozen bed. I just ran the full integration test (`/pscratch/sd/a/ahager/PRtesting/full_integration/allowInteriorBoundaries`) on it but the baseline comparisons for the humboldt hydro test cases both failed. The discrepancy is really small (differences in hydropotential between the baseline and test cases are < 0.3 Pa), but I haven't been able to identify their cause. When you get a chance, could you take a look at the changes? Matt suggested I have you review the PR in his absence

2024-03-26 02:50 UTC, trhille requested changes
The slight discrepancy in the Humboldt runs might be due to dropping the dependence on vertices at the edge of the mesh. See comment below.

2024-03-26 02:50 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               totalGroundingLineDischargeEdge(iEdge) = abs(channelDischarge(iEdge)) +abs( waterFlux(iEdge) * dvEdge(iEdge))
```suggestion
               totalGroundingLineDischargeEdge(iEdge) = abs(channelDischarge(iEdge)) + abs( waterFlux(iEdge) * dvEdge(iEdge))
```

2024-03-26 02:50 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +
```suggestion
```

2024-03-26 02:50 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +            if ( ((cell1 == nCells + 1) .or. (cell2 == nCells +1 )) &
```suggestion
            if ( ((cell1 == nCells + 1) .or. (cell2 == nCells + 1 )) &
```

2024-03-26 02:50 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +            ! check for edges on no-flow boundaries (which should include boundaries of the mesh) and zero the tangent slope there
This seems like a slightly different treatment from the code that it replaces. Could this be the source of the small differences in the integration suite runs?

2024-03-26 15:13 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +            ! check for edges on no-flow boundaries (which should include boundaries of the mesh) and zero the tangent slope there
Update: I tried reverting these lines to the previous treatment and the Humboldt hydro tests still fail baseline comparison, so I guess this isn't the culprit.

2024-03-26 15:29 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +            ! check for edges on no-flow boundaries (which should include boundaries of the mesh) and zero the tangent slope there
Good catch, I still think these lines would cause issues but might not be the whole problem. What `config_SGH_tangent_slope_calculation` are you using in the integration suite? The default is `from_normal_slope`, so these lines weren't even being used in the test I was running (although I know eventually we should run the integration test on both options)

2024-03-26 15:38 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +            ! check for edges on no-flow boundaries (which should include boundaries of the mesh) and zero the tangent slope there
Yeah, the integration suite just uses the default. I hadn't noticed that these lines weren't being used.

2024-03-26 15:53 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               (waterFluxMask(iEdge) == 2) ) then
Is this necessary? This also could result in different behavior from the baseline. Testing now.

2024-03-26 16:03 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               (waterFluxMask(iEdge) == 2) ) then
That's true, I always forget if (.not. li_mask_is_ice) would include domain boundaries. If not, then I think we want to keep that in

2024-03-26 16:20 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               (waterFluxMask(iEdge) == 2) ) then
Reverting this change did not help.

2024-03-26 16:47 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               (waterFluxMask(iEdge) == 2) ) then
![Screenshot 2024-03-26 at 9 37 44 AM](https://github.com/MALI-Dev/E3SM/assets/131483939/b55017cd-fade-4b86-bc6a-96cfcac1bd3d)
![Screenshot 2024-03-26 at 9 38 24 AM](https://github.com/MALI-Dev/E3SM/assets/131483939/858085bf-3904-4df0-93ea-1b542ef678f2)
The `waterFluxMask` here is necessary to zero out `hydropotentialSlopeTangent` at the domain boundaries, but that previously this wasn't done in. I believe this is something that still makes sense to do, even if it very slightly changes the output. Odd though that reverted it doesn't help the integration test; there must be something else wrong too

2024-03-26 16:48 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               (waterFluxMask(iEdge) == 2) ) then
In above plots, `develop` is left and this PR is right

2024-03-26 16:53 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +               (waterFluxMask(iEdge) == 2) ) then
Oh good catch!

2024-04-05 20:58 UTC, closed without merging