Do not update FCT masks between RK stages
MALI-Dev/E3SM pull request #110
Opened 2024-04-02 03:19 UTC by trhille

Do not update FCT masks between RK stages. The masking for FCT is now calculated in the first RK stage and not updated again in the time step.

2024-04-03 21:30 UTC, mperego approved these changes
It looks good to me. Thanks.

2024-08-15 02:42 UTC, matthewhoffman requested changes
@trhille , sorry for letting this sit for so long.  After spending some time with it, I'm confident the implementation is correct, and the reason for keeping the FCT masks fixed between RK stages makes sense.  The only question left is what additional testing, if any, should be done.  I can see two levels of complexity here: 1. ensure that for changing ice extent (retreat or advance) the code runs without error and produces results that look as expected, or 2. for changing ice extent, evaluate order of accuracy with and without this change.  We know we can only expect first order accuracy when the margin changes, but perhaps before this change we are seeing noticeably worse than first order.  I'm content to go with option 1.  What do you think about testing?

Other than that, I added two very minor requests.

2024-08-15 02:42 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +               MPAS_LOG_ERR, masterOnly=.true.)
Why `masterOnly`?  It seems possible that the error only occurs on a different processor and then it doesn't get written anywhere.  Side note, I didn't remember that option existing but apparently I wrote it.

2024-08-15 02:42 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
>           if (err1 /= 0 .or. err2 /= 0) then
```suggestion
         if (err2 /= 0) then
```

Might be able to remove `err2` from the subroutine and replace this instance with `err`.  I haven't looked carefully.

2024-08-15 21:41 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +               MPAS_LOG_ERR, masterOnly=.true.)
Probably a copy-paste oversight. I'll remove.

2024-08-15 22:32 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
>           if (err1 /= 0 .or. err2 /= 0) then
Fixed in https://github.com/MALI-Dev/E3SM/pull/110/commits/c0f079e10a3c5fc33034db3a095a3f8c873b70bd.

2024-08-15 22:32 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +               MPAS_LOG_ERR, masterOnly=.true.)
Removed in https://github.com/MALI-Dev/E3SM/pull/110/commits/c0f079e10a3c5fc33034db3a095a3f8c873b70bd.

2024-08-15 22:48 UTC, trhille commented
@matthewhoffman, regarding testing, we know this is a necessary change, but it's probably not sufficient. So I think option 1 (ensuring reasonable behavior without formally establishing convergence) is fine. 
@mperego, what do you think?

2024-08-15 22:57 UTC, mperego commented
> @matthewhoffman, regarding testing, we know this is a necessary change, but it's probably not sufficient. So I think option 1 (ensuring reasonable behavior without formally establishing convergence) is fine. @mperego, what do you think?

I agree.

2024-08-16 03:43 UTC, trhille commented
Testing
-------
I tested this on the 2km mismip mesh with a two-phase experiment with this branch rebased onto `MALI-Dev/develop`, compared with the head of `MALI-Dev/develop`. I used 3-stage RK3, 3rd order advection with `config_advection_coef_3rd_order = 1.0`. Basal melting and thermodynamics were turned off. Advective and calvign CFL fractions were set to 0.8.

Phase 1: 50-yr retreat with a specified calving velocity of 2km/yr. Flow velocity is ~1km/yr so this leads to ~50 km retreat.
Phase 2: 30-yr advance with calving turned off. I ran this for a shorter duration so that the ice shelf would not reach the calving mask at the domain edge.

Phase 1 results:
Top panel: using head of `develop` at end of phase 1
Middle panel: this branch rebased onto `develop`at end of phase 1
bottom: difference
![image](https://github.com/user-attachments/assets/f6ef72dd-3ed4-4537-b921-34f44681f822)

2024-08-16 16:01 UTC, matthewhoffman commented
@trhille thanks for adding that test results, including the thickness differences.  The differences are small enough that I think proceeding with this PR makes sense.  It looks like the old method retreats about one row farther and advances about row cell farther than the new method, but I can't think of an argument if which is more correct either way.  

(Side note - both versions seem to have a slight elevated ridge along the calving front in the advancing case, which is not realistic.  That's unrelated to this PR of course, but interesting to note.)

@mperego , I know you already approved this ages ago, but based on these new results, do you think we should look further into anything?  If not, I will go ahead and approve and merge as-is.

2024-08-16 19:49 UTC, mperego commented
Yes, I think it's fine to merge.

2024-08-16 20:52 UTC, trhille commented
Note: I've confirmed that the clear thickness artifacts at the advancing ice front in the figures above are the result of using too large a time step. A run with an advective CFL fraction of 0.2 exhibits a much smoother ice front. here's a transect from that run in blue vs from the CFL fraciton 0.8 run in the figures above, after fifteen years of advance:
![image](https://github.com/user-attachments/assets/f43ed4cc-2387-4e33-a5f6-ac9c88089eb5)

2024-08-19 20:49 UTC, trhille commented
I've confirmed that this change leads to minimal differences in the Halfar dome convergence test, using 2nd order FCT and RK2. One panel is head of `develop`, the other is this branch rebased onto `develop`:
![image](https://github.com/user-attachments/assets/53ab777d-0dc7-4ee3-8bfc-216f567044f6)

Here is the thickness difference at year 200 (calculated using `ncdiff`, so it says `year = 0.00` because it differenced `daysSinceStart` as well as the relevant fields):
![image](https://github.com/user-attachments/assets/a298ac76-611a-475a-b826-b1e771be3bb9)

2024-08-20 03:18 UTC, matthewhoffman approved these changes
@trhille , thanks for making those small changes and doing all that additional testing.  It is quite informative to know how this change affects the convergence tests, and I feel more confident proceeding knowing the differences are so slight.

I reran the full_integration suite on perlmutter and everything passes.

2024-08-20 03:18 UTC, merged