New Variable: Total grounding line discharge entering adjacent ocean cell
MALI-Dev/E3SM pull request #112
Opened 2024-04-04 21:31 UTC by alexolinhager

This PR adds a small subroutine to the hydro model that calculates a new variable, `totalGroundingLineDischargeCell`, that is needed to couple the hydro model to MPAS-Ocean. `totalGroundingLineDischargeCell` is the total volume flux (distributed + channelized; units: m3 s-1) entering each ocean cell adjacent to the grounding line. Distributed and channelized flow at each grounding line edge is summed into `totalGroundingLineDischargeEdge` and that value is extrapolated to the adjacent ocean cell. If multiple grounding line edges border the same ocean cell, then `totalGroundingLineDischargeEdge` values at all adjacent edges are summed to form `totalGroundingLineDischargeCell` for that cell.

2024-04-04 21:32 UTC, alexolinhager commented
The PR passes the full integration suite at commit `57a370e`

2024-04-05 17:59 UTC, matthewhoffman requested changes
@alexolinhager , thanks for creating this PR.  I have a few minor changes to request.

I also had a question of if we actually need the edge version of the GL flux - I'm not sure of the answer.  I was also wondering if while you're doing this if we should create distributed and channel versions in case we ever want to handle them differently in the ocean model in the future.  Or we could wait until we need that.

2024-04-05 17:59 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> -!!      type (mpas_pool_type), pointer :: geometryPool
There is a long series of changes to this subroutine that are just variable declarations and mpas_pool_get calls, but no actual changes to the operations - those should all be removed from the PR.

2024-04-05 17:59 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +            ! other cell floating ice or open ocean
this comment doesn't make sense here

2024-04-05 17:59 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +                 ((bedTopography(cell2) < config_sea_level) .and. (.not. li_mask_is_ice(cellMask(cell2)))) ) ) then
Here, it is only necessary to check which cell is the grounded one:
```suggestion
            if (li_mask_is_grounded_ice(cellMask(cell1))) then
```

2024-04-05 17:59 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +                     ((bedTopography(cell1) < config_sea_level) .and. (.not. li_mask_is_ice(cellMask(cell1)))) ) ) then
similar change to previous

2024-04-05 17:59 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry_subglacial_hydro.xml
> +
remove this whitespace change

2024-04-05 17:59 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry_subglacial_hydro.xml
> +		     description="total discharge across grounding line edge" />
Is this field necessary?  I don't remember what we decided with the ocean folks.  I know we want the cell version, but I don't remember if there is potential value to also having the edge version.

2024-04-05 23:10 UTC, alexolinhager commented
@matthewhoffman I added two more commits: The first addresses your comments cleaning up the code and the second calculates the distributed and channelized versions of `totalGroundingLineDischargeCell`, as you suggested. I figure we should add them to the code now instead of wishing we had run with those variables later on. I also removed totalGroundingLineDischargeEdge from the registry because it won't be used by MPAS-Ocean

2024-04-05 23:11 UTC, alexolinhager commented
The PR also passes the full integration suite so should be good to merge if you give it your stamp of approval

2024-04-08 21:18 UTC, matthewhoffman requested changes
@alexolinhager , thanks for revising this.  I have requested a few more small changes.

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry_subglacial_hydro.xml
> +		     description="distributed discharge across the grounding line, extrapolated from edge to adjacent ungrounded cell. Values from all edges are summed if multiple grounding line edges border a sin
```suggestion
		     description="distributed discharge across the grounding line, summed from grounding line edges to adjacent ungrounded cell. Values from all edges are summed if multiple grounding line edges border a single ungrounded cell" />	
```

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry_subglacial_hydro.xml
> +		     description="total (channel + dist.) discharge across the grounding line, extrapolated from edge to adjacent ungrounded cell. Values from all edges are summed if multiple grounding line edges
```suggestion
		     description="total (channel + dist.) discharge across the grounding line, summed from grounding line edges to adjacent ungrounded cell. Values from all edges are summed if multiple grounding line edges border a single ungrounded cell" />	
```

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry_subglacial_hydro.xml
> +		     description="channel discharge across the grounding line, extrapolated from edge to adjacent ungrounded cell. Values from all edges are summed if multiple grounding line edges border a single
```suggestion
		     description="channel discharge across the grounding line, summed from grounding line edges to adjacent ungrounded cell. Values from all edges are summed if multiple grounding line edges border a single ungrounded cell" />	
```

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> -!!      type (mpas_pool_type), pointer :: geometryPool
@alexolinhager , looks like this series of changes is still in the PR.  Let me know if you need help figuring out how to get rid of them.

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +      call mpas_timer_stop("halo updates")
There isn't a halo update on the new variables you added on Friday and edge-version variable is still here, which I would expect would cause an error.  But now that I'm thinking about it, we don't actually need halo updates on these variables.  The values in the halo regions will be incorrect, but the fields are not used for any internal calculations, and the halo regions don't get used when the fields get written to output.  So I think the best thing is just delete these halo updates.

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +      real (kind=RKIND), pointer :: config_sea_level
remove this unused variable here and below at 2350

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +      real (kind=RKIND), dimension(:), pointer :: bedTopography
remove this unused variable here and below

2024-04-08 21:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         cell2 = cellsOnEdge(2, iEdge)
would be more slightly efficient to move these inside the if-statement

2024-04-10 00:09 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> -!!      type (mpas_pool_type), pointer :: geometryPool
@matthewhoffman I thought I got rid of all extra changes in that subroutine. All of the extra variable names have been deleted from what I can tell. I had accidentally removed `nEdgesSolve` then had to add it back in, which is why that is there as a change now. The remaining changes were me cleaning up the script and removing blank lines left after removing the extra variable names. Are there more changes I should get rid of?

2024-04-10 02:19 UTC, matthewhoffman approved these changes
@alexolinhager , I'm still seeing some whitespace changes, but it's not that important and I don't want to hold up this PR any longer.  Other than that, everything looks good.  I'll get this merged.

2024-04-10 02:19 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +
```suggestion

```

2024-04-10 02:43 UTC, matthewhoffman commented
# Testing
All tests pass `full_integration` on Chicoma

2024-04-10 02:44 UTC, merged