Ice Margin Boundary Condition Alterations
MALI-Dev/E3SM pull request #118
Opened 2024-05-22 14:53 UTC by alexolinhager

Make changes to boundary conditions at the grounding line to improve stability in ice dynamics-hydrology coupled runs. Most problems were arising because of very weak gradients at the grounding line formed from a thinning glacier. The primary changes in this PR are zeroing out `hydropotential` and `waterPressure` in the ocean, and instating a small outflowing condition at grounding line edges (instead of zeroing out `channelArea` and `channelDischarge` to prevent inflow). 

This PR is a compilation of cherry-picked commits originally made on a separate mega-branch ([https://github.com/MALI-Dev/E3SM/tree/alexolinhager/chnlInstabilityDebugging]). As of now, the commits in this PR have been tested on the Thwaites coupled domain as part of the other branch, but this subgroup has not been tested as its own branch. Testing should be done on the Thwaites coupled domain and full integration suite before merging.

2024-05-22 16:46 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +      real (kind=RKIND), parameter :: MIN_PHISLOPE_GL = 1e-10_RKIND
move to module level variable

2024-05-22 16:46 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> -                  waterPressure(iCell) = rhoo * gravity * (config_sea_level - bedTopography(iCell))
this might still be necessary because channelization could cause hydropotential adjacent to the boundary to drop below sea level.

2024-05-22 16:46 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         hydropotentialBase = 0.0_RKIND !zero hydropotential where no grounded ice
* revisit if we want this to be zero on land 
* replace 0 with SEALEVEL module variable

2024-05-22 16:46 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> -      ! Disable channels from forming if there is no sheet flux
we agreed this should go

2024-05-22 16:46 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         waterPressure = 0.0_RKIND ! zero waterPressure where no grounded ice
replace with UNDEF value

2024-05-23 16:13 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         hydropotentialBase = 0.0_RKIND !zero hydropotential where no grounded ice
Revisiting this, I'm a little confused why we don't want to keep hydropotential and hydropotentialBase as 0 in the ocean, instead of equal to config_sea_level. There is also a difference in units (m vs. Pa), so we would have to do unit conversion. We could try defining SEALEVEL as the difference in mean atm pressure at the ocean surface relative to today's global mean sea level, but then I'm also having a hard time conceptualizing in what situation this would be used. The hydropotential should adjust to meet any raise or drop in sea level, so should be zero in the ocean no matter what sea level is. Does that make sense or am I missing something?

2024-05-23 16:46 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         hydropotentialBase = 0.0_RKIND !zero hydropotential where no grounded ice
Also, I think `hydropotential` should technically be defined everywhere, so we should keep our definition of hydropotential on ice-free land as `rho*g*Z_b`. In practice though, it doesn't really matter how we define it on land, because the one-sided treatment of hydropotential slopes at terrestrial boundaries ignores anything outside of the active hydro domain. But I think it would be good to have a consistent definition of hydropotential throughout the domain.

I'm cleaning up the hydropotential slope section and changing some comments to make it more clear what's actually going on there.

2024-05-23 17:27 UTC, alexolinhager commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         waterPressure = 0.0_RKIND ! zero waterPressure where no grounded ice
Note that we should think carefully about how changes here affect the calculation of waterPressureSlope at the grounding line

2024-05-23 19:22 UTC, alexolinhager commented
I pushed another commit making minor changes in regards to yesterday's comments. Hopefully the additional commenting around the hydropotential slope calculations makes it more obvious what's going on. I'll wait until we have a consensus on how to handle hydropotential and waterPressure to make the rest of the changes.

2024-06-28 19:09 UTC, alexolinhager commented
@matthewhoffman, I pushed a few more commits that get the PR to where we want it. The current version current passes the hydro_radial validation and baseline comparison; however, it fails the Humboldt baseline comparison because the changes we made to the marine boundary. The differences between the baseline and this PR are quite minor. This PR also behaves normally for the Thwaites domain. I think we are at a point where this could be merged.

![Screenshot 2024-06-28 at 11 35 57 AM](https://github.com/MALI-Dev/E3SM/assets/131483939/09b6fb30-efd9-4dbd-b0d4-d86476df6097)

Small change in waterThickness near grounding line: 
![Screenshot 2024-06-28 at 11 45 06 AM](https://github.com/MALI-Dev/E3SM/assets/131483939/0909a322-6bac-4ad5-a115-de51fcf85143)

Small changes in hydropotential near grounding line (black are cells at or below sea level):
Beginning of run:
![Screenshot 2024-06-28 at 11 47 04 AM](https://github.com/MALI-Dev/E3SM/assets/131483939/d1c706bd-c2ce-4a50-9cad-22718b231fcc)

End of run:
![Screenshot 2024-06-28 at 11 46 15 AM](https://github.com/MALI-Dev/E3SM/assets/131483939/db65c1a7-14f5-4f76-ab3c-78ed58c8718a)

All of the differences from `develop` are near the grounding line, and are what I would expect given the changes to the code

2024-08-14 19:31 UTC, matthewhoffman requested changes
@alexolinhager , thanks for your patience in me reviewing this.  All the changes make sense, and I only have minor changes to request.  I'm running compass tests on this version now.

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
>           endif ! if edge of grounded ice
let's update these comments to be consistent with the revised logic

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
>           endif ! if edge of grounded ice
same as previous comment

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         elsewhere ((.not. (li_mask_is_grounded_ice(cellMask))) .and. (bedTopography < config_sea_level))
```suggestion
         elsewhere ((.not. (li_mask_is_grounded_ice(cellMask))) .and. (bedTopography <= config_sea_level))
```

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
>           end where
The logic covers all possible combinations, but if there is a nan, all checks will fail and those cells won't be updated (will maintain whatever previous value they had).  Let's add an elsewhere that inserts nan.

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +         elsewhere ((.not. (li_mask_is_grounded_ice(cellMask))) .and. (bedTopography < config_sea_level))
```suggestion
         elsewhere ((.not. (li_mask_is_grounded_ice(cellMask))) .and. (bedTopography <= config_sea_level))
```

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +      where ((.not. li_mask_is_grounded_ice(cellMask)) .and. (bedTopography < config_sea_level))
```suggestion
      where ((.not. li_mask_is_grounded_ice(cellMask)) .and. (bedTopography <= config_sea_level)) 
```

2024-08-14 19:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_subglacial_hydro.F
> +      ! Similar to waterFlux, shut of channelDischarge if no water upstream. Prevents self-sustaining channels in the absence of distributed water
```suggestion
      ! Similar to waterFlux, shut off channelDischarge if no water upstream. Prevents self-sustaining channels in the absence of distributed water
```

2024-08-14 20:26 UTC, matthewhoffman commented
# Testing

Ran compass full_integration suite on Perlmutter.  The 4 hydro tests failed baseline comparison, as expected, but otherwise everything passes.

```
Test Runtimes:
00:26 PASS landice_dome_2000m_sia_restart_test
00:14 PASS landice_dome_2000m_sia_decomposition_test
00:21 PASS landice_dome_variable_resolution_sia_restart_test
00:54 PASS landice_dome_variable_resolution_sia_decomposition_test
00:26 PASS landice_enthalpy_benchmark_A
00:31 PASS landice_eismint2_decomposition_test
00:21 PASS landice_eismint2_enthalpy_decomposition_test
00:29 PASS landice_eismint2_restart_test
00:20 PASS landice_eismint2_enthalpy_restart_test
00:09 PASS landice_greenland_sia_restart_test
00:16 PASS landice_greenland_sia_decomposition_test
00:18 FAIL landice_hydro_radial_restart_test
00:10 FAIL landice_hydro_radial_decomposition_test
00:30 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-none_subglacialhydro
00:30 FAIL landice_humboldt_mesh-3km_restart_test_velo-none_calving-none_subglacialhydro
00:26 PASS landice_dome_2000m_fo_decomposition_test
00:29 PASS landice_dome_2000m_fo_restart_test
00:26 PASS landice_dome_variable_resolution_fo_decomposition_test
00:16 PASS landice_dome_variable_resolution_fo_restart_test
00:31 PASS landice_circular_shelf_decomposition_test
00:45 PASS landice_greenland_fo_decomposition_test
00:46 PASS landice_greenland_fo_restart_test
00:26 PASS landice_thwaites_fo_decomposition_test
00:34 PASS landice_thwaites_fo_restart_test
00:18 PASS landice_thwaites_fo-depthInt_decomposition_test
00:39 PASS landice_thwaites_fo-depthInt_restart_test
00:45 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
00:29 PASS landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 13:00
FAIL: 4 tests failed, see above.
```

2024-08-20 02:33 UTC, matthewhoffman approved these changes
@alexolinhager , thanks for making the adjustments.  It all looks good.  I retested with the integration suite and get the same results - the 4 hydro tests fail baseline comparison but everything else passes.

2024-08-20 02:34 UTC, merged