Updates to ocean thermal forcing extrapolation and diagnosing
MALI-Dev/E3SM pull request #123
Opened 2024-08-27 22:31 UTC by cshafer

This PR makes changes to two scripts: (1) the ocean extrapolation script to generalize the `validOceanMask` and (2) the ice shelf melting script to diagnose issues related to grounded face melting. 

- The ocean extrapolation script was originally written to take in a 2d ocean mask `origOceanMaskHoriz` that is projected down through the ocean layers to create a 3d `validOceanMask`. We instead generalize the code to take in as input a 3d mask called `orig3dOceanCavityMask` that `validOceanMask` is set to. We also update a typo that makes sure that locations outside the `validOceanMask` (and not the `availOceanMask`) are set to the `invalid_value_TF` value.

- In the ice shelf melting script, we modify which ocean level is used to populate `TFocean`. Previously, there was a step that interpolated between ocean layers if the bedrock topography existed between the two but was neither more shallow that the first ocean layer nor deeper than the bottom ocean layer. However, it is possible that the deeper ocean layer below the bedrock topography could contain invalid TF values, and so we modify it to take valid TF data only from above the bedrock topography as opposed to interpolating between the two layers.

- If the bedrock topography is more shallow than the first ocean layer, then we keep `kk = 1` since there is no 'good' ocean layer to switch to. In this case, `TFocean` could still get invalid TF values.

- I also add a check to see whether `TFocean` is being populated with invalid TF values. This will need to be updated to check for invalid values where there should be valid extrapolated TF data in grounded locations as opposed to checking for invalid TF values anywhere.

2024-08-28 02:25 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         call mpas_timer_start("halo updates")
@matthewhoffman removed these halo updates in https://github.com/MALI-Dev/E3SM/commit/8b8e18b1ff44727e300617c94b0a33b45660755e. Looks like these got entrained during the rebase.

2024-09-06 23:36 UTC, alexolinhager requested changes
These changes look good to me! I made a few minor suggestions for edits to the code, but most of my comments are regarding the naming structure of the various masks. I know the naming convention was established in a different PR, but I feel like it's quite challenging to keep track of all of the different mask definitions/names, especially because a lot of them use very similar wording. I added a comment that may help fix this and make it more user friendly.

2024-11-21 00:31 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         call mpas_allocate_scratch_field(seedMaskField, single_block_in = .true.)
Thanks for flagging.  Yes this is correct (it's how scratch fields are used).

2024-11-21 00:33 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         growMask(:) = 0
For better or worse, the `li_flood_fill` routine below requires these variable names are used.

2024-11-21 00:35 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +            if ((ismip6shelfMelt_zBndsOcean(1,iLayer) > 0.0_RKIND) .or. &
No, the `if ((ismip6shelfMelt_zBndsOcean(2,iLayer) >= 0.0_RKIND) ...` line below combined with this line will together cover the range of possibilities.

2024-11-21 00:42 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
>        integer, dimension(:), pointer :: origOceanMaskHoriz
Fixed in d52cea7f4c

2024-11-21 00:43 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
>           call mpas_pool_get_array(extrapOceanDataPool, 'origOceanMaskHoriz', origOceanMaskHoriz)
Fixed in d52cea7f4c

2024-11-21 00:43 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         connectedmarineMask(:) = 0
Fixed in d52cea7f4c

2024-11-21 00:44 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +            if ((ismip6shelfMelt_zBndsOcean(1,iLayer) > 0.0_RKIND) .or. &
Addressed in d52cea7f4c.
(The commit message refers to the fact that if zBndsOcean was not populated, those tests would fail.)

2024-11-21 00:44 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
>           validOceanMask(:,:) = 0
Fixed in d52cea7f4c

2024-11-21 03:48 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                     description="3D mask for original valid ocean data that includes cavities (e.g., SORRM original TF data)"
@alexolinhager , thanks for the suggestions on this - it's been confusing for awhile.  I followed your suggestion for 3.  The "Cavity" part of the name is inaccurate so it makes sense to remove that.  I did not remove any variables from Registry because having them in Registry allows them to be added to an output stream, which is very helpful for debugging.  I also did not rename any other variables to avoid messing up your subsequent branch and to keep things simple.  I did, however, vastly lengthen the description of each variable in Registry.  Hopefully that helps reduce confusion about how they are all used.

2024-11-21 03:50 UTC, matthewhoffman commented
@alexolinhager , after a long delay, I've made revisions to this PR based on your review.  Please re-review and make sure I've addressed your concerns.  It will be good to get this finally merged.  Note that I resolved most of your comments, but I added responses before resolving them, so you can see the responses if you like.

2024-11-21 17:41 UTC, alexolinhager approved these changes
Thanks @matthewhoffman for making these changes. They all look good to me; particularly, the expanded variable definitions make the code a lot easier to interpret.

2024-11-21 19:17 UTC, matthewhoffman commented
Passes `full_integration` on pm-cpu.

2024-11-21 19:17 UTC, merged