Stephenprice/glc/mali updates
MALI-Dev/E3SM pull request #16
Opened 2021-11-19 21:11 UTC by stephenprice

Update Greenland ice sheet support for MALI in E3SM

This pull request updates support for conducting simulations with a dynamic Greenland
ice sheet in E3SM using MALI. Updates include:

- update Albany library path
- update filename associated with GIS 1to10 km init. cond.
- commenting out (temporarily?) excessive land model warnings that degrade performance

These changes have been tested in both IG and BG compsets and run for one year at 5 day timesteps 
and 5 day glc coupling intervals. Results were examined qualitatively and deemed to be reasonable 
and realistic. Solver performance was quite uniform throughout (linear and nonlinear iteration counts 
consistently below 20 and closer to ~10).

2021-11-19 23:25 UTC, stephenprice commented
Note that Anvil / Chrys were down when c753c8 was pushed, so while file support for this commit currently exists on Cori, the relevant input data file still needs to be scp'd to Anvil before this is fully operational.

2021-11-20 00:11 UTC, mperego commented
@stephenprice This looks good to me. 
I'm wondering what's the best approach with the warnings. That is, should we discuss with the glc folks what's the best solution before we comment them out in the MALI-Dev develop branch, or is it OK to temporarily commenting these out in the MALI-Dev develop branch, and think about that when we want to merge into E3SM? Maybe @matthewhoffman has a strong opinion on this.

2021-11-22 21:01 UTC, matthewhoffman commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
It looks like this datestamp is month-day-year.  Previously we had been using year, month, day, which is what E3SM typically uses I think.  We should make use of that convention here, and switch to using a 4 digit year to reduce potential confusion (like in the AIS datestamp a few lines prior).

2021-11-22 21:05 UTC, matthewhoffman commented
Regarding the excessive comments, it's not clear to me who 'owns' that code, but I think we will should due our due diligence now to figure out what the proper solution is and if anyone has objections or preferences.  I think that means checking with the Land model team as well as Rob Jacob or someone on Infrastructure.  I'd prefer to resolve that in this PR than wait until we try to merge back to the main E3SM repo.

2021-11-22 21:06 UTC, matthewhoffman requested changes
@stephenprice , thanks for getting this PR opened.

See comments above for review notes.

2021-11-23 16:42 UTC, matthewhoffman commented on driver-mct/main/map_glc2lnd_mod.F90
> +!          write(logunit,*) subname, ': WARNING, for glc_pt, topo = ', glc_pt, glc_topo(glc_pt)
Rather than commenting out this warning about glacier topo height out of range, let's figure out why it's going out of range and then either fix that or adjust the possible ranges.

I think the problem is that we set glacier topo height from upperSurface in MALI, but the way upperSurface is defined in MALI it is set to the bedTopography where there is no ice, which leads to values below sea level.  Try the following change without commenting these warnings, and see if that keeps the warnings from being printed.

```
diff --git a/components/mpas-albany-landice/driver/glc_comp_mct.F b/components/mpas-albany-landice/driver/glc_comp_mct.F
index 9418e61267..c941974a1b 100644
--- a/components/mpas-albany-landice/driver/glc_comp_mct.F
+++ b/components/mpas-albany-landice/driver/glc_comp_mct.F
@@ -1475,7 +1475,7 @@ contains
             g2x_g % rAttr(index_g2x_Figg_rofi,n)=0.0 !...and remove these placeholders
             g2x_g % rAttr(index_g2x_Fogg_rofl,n) = 0.0 !Attach to subglacial liquid flux once present

-            g2x_g % rAttr(index_g2x_Sg_topo, n) = upperSurface(i)
+            g2x_g % rAttr(index_g2x_Sg_topo, n) = max(0.0, upperSurface(i))
             g2x_g % rAttr(index_g2x_Sg_tbot, n) = temperature(nVertlevels,i) - SHR_CONST_TKTRIP
             ! layerThickness is not populated on init, so calculating like this instead:
             g2x_g % rAttr(index_g2x_Sg_dztbot, n) = layerThicknessFractions(nVertLevels) * thickness(i) / 2.0
```

2021-11-29 22:51 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
I can make that change if it should be yymmdd. But to be clear, I used that format to be consistent with the existing "grid date" (and the "decomp date") for newer files. E..g. if you look at the file names for the GIS 1-to-10 km grid a few lines farther down they appear to also use mmddyy. 

If we agree we should be using yymmdd, should I update the support and filenames for the GIS 1-to-10 km grid / decomp files as well?

2021-11-29 22:57 UTC, stephenprice commented on share/nuopc/glc_elevclass_mod.F90
> +!          write(logunit,*) subname, ': WARNING, for glc_pt, topo = ', glc_pt, glc_topo(glc_pt)
done

2021-11-29 23:52 UTC, stephenprice commented on driver-mct/main/map_glc2lnd_mod.F90
> +!          write(logunit,*) subname, ': WARNING, for glc_pt, topo = ', glc_pt, glc_topo(glc_pt)
This appears to work. Thanks for the suggestion. I will commit that change here as well.

2021-11-30 00:18 UTC, stephenprice commented
@matthewhoffman - I will see what I can do about better understanding what the warning on line 347 of `./components/elm/src/biogeophys/BalanceCheckMod.F90` is about. 

Please see my additional comments about date conventions for input files in the repository.

2021-11-30 00:36 UTC, mperego commented on components/elm/src/biogeophys/BalanceCheckMod.F90
> +!          write(iulog,*)'WARNING:  glc_dyn_runoff_routing = ', glc_dyn_runoff_routing(g)  ! TKT
What about this warning? Is this still related to the the upper surface being negative?

2021-11-30 00:41 UTC, mperego commented on components/elm/src/biogeophys/BalanceCheckMod.F90
> +!          write(iulog,*)'WARNING:  glc_dyn_runoff_routing = ', glc_dyn_runoff_routing(g)  ! TKT
@stephenprice never mind, I hadn't seen your comment.

2021-11-30 02:59 UTC, stephenprice commented on components/elm/src/biogeophys/BalanceCheckMod.F90
> +!          write(iulog,*)'WARNING:  glc_dyn_runoff_routing = ', glc_dyn_runoff_routing(g)  ! TKT
I contacted Teklu at PNNL by email about this warning as git blame indicates it was part of a large set of commits he worked on 7 or so months ago. It's not obvious that I can flag him directly from this discussion thread (I could not find his github name accessible here).

2021-11-30 15:15 UTC, matthewhoffman commented on driver-mct/main/map_glc2lnd_mod.F90
> +!          write(logunit,*) subname, ': WARNING, for glc_pt, topo = ', glc_pt, glc_topo(glc_pt)
Glad that worked.  Thanks for updating the PR

2021-11-30 15:16 UTC, matthewhoffman commented on share/nuopc/glc_elevclass_mod.F90
> +!          write(logunit,*) subname, ': WARNING, for glc_pt, topo = ', glc_pt, glc_topo(glc_pt)
I'm asking for clarification on the preferred convention, and then we can standardize it.

2021-12-02 17:54 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
@matthewhoffman - to be clear, this comment from you below ...

> I'm asking for clarification on the preferred convention, and then we can standardize it.

... is in the context of the date stamp convention question, correct?

2021-12-02 17:59 UTC, stephenprice commented on share/nuopc/glc_elevclass_mod.F90
> +!          write(logunit,*) subname, ': WARNING, for glc_pt, topo = ', glc_pt, glc_topo(glc_pt)
The response from Teklu is that this was only in there for debugging purposes, so we have approval of the land team to leave this commented out.

2021-12-02 18:00 UTC, stephenprice commented on components/elm/src/biogeophys/BalanceCheckMod.F90
> +!          write(iulog,*)'WARNING:  glc_dyn_runoff_routing = ', glc_dyn_runoff_routing(g)  ! TKT
The response from Teklu is that this was only in there for debugging purposes, so we have approval of the land team to leave this commented out.

2021-12-02 18:01 UTC, mperego commented on components/elm/src/biogeophys/BalanceCheckMod.F90
> +!          write(iulog,*)'WARNING:  glc_dyn_runoff_routing = ', glc_dyn_runoff_routing(g)  ! TKT
thanks for taking care of that.

2021-12-02 20:41 UTC, matthewhoffman commented
@xylar  this is a test message trying to call someone outside the MALI-Dev organization.  Please ignore.

2021-12-02 23:49 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
I talked w/ Jon W. on this ...

> [for] MPAS data files we've been using yymmdd -- at least for ocn/ice

So I will change that for the new file. Then I'd like thoughts on if I should update the other filenames in there to be consistent (init. cond. files, all older now, and grid decomp. files). If we change those, I will also change the relevant e3sm code that might access them.

2021-12-02 23:54 UTC, mperego commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
If you are thinking of updating all the files, why don't we go with the yyyymmdd convention?

2021-12-03 20:40 UTC, matthewhoffman commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
Yes, i was talking the date stamp convention.  I heard back - Rob Jacob said "use YYYYMMDD if you can", but we don't need to worry about going back and cleaning up previous instances that don't follow that unless we want to.

2021-12-06 16:21 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
Hmmm, ok. You all are ok with adding 2 more digits to every filename from here on out? If that is consistent w/ what other e3sm components are doing then I guess we should probably go w/ that too. I guess we can be optimistic and assume these files / this project will still be around in the year 3000 and beyond.

2021-12-06 16:36 UTC, matthewhoffman commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
I like the 2 extra digits.  Not so much that we expect a Y2K situation, but that it makes it easier to visually parse what you are looking at, especially for new people.  Based on Rob's comment, we should use YYYYMMDD with this new file and going forward, but let's not bother renaming existing files.

2021-12-06 18:07 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
I'll try to make those changes and push them later today.

2021-12-06 22:04 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '111921'
This file name has been updated in the repo on Anvil and tested on Cori to make sure that 1) the file is pulled down automatically upon case.submit (if not already available) and 2) the file works in a 10-day test run.

2021-12-06 22:04 UTC, stephenprice commented
@matthewhoffman, @mperego - I think all the outstanding items in the PR have been addressed now. Please take a look and let me know when you have a chance. Thanks.

2021-12-06 22:09 UTC, mperego commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '082421'
Does this need to be updated as well?

2021-12-06 23:56 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '082421'
The consensus was (I think) to leave older filenames as is and only change them to the new format if/when they are updated. @matthewhoffman, correct me if that is wrong.

2021-12-07 00:30 UTC, mperego commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '082421'
but wasn't this updated? Anyway, I'm fine either way.

2021-12-07 02:28 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '082421'
I guess it depends on where we draw the line here between 'older' and 'newer' files. But you are right in that a main part of this PR into e3sm was to update the support for the 1to10km file too. So, I will go ahead and make that fix as well.

2021-12-07 04:35 UTC, mperego commented
Thanks @stephenprice, looks good to me!

2021-12-10 15:51 UTC, matthewhoffman commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '20210824'
@stephenprice , it looks like we still need to put this grid file on Anvil here: https://web.lcrc.anl.gov/public/e3sm/inputdata/glc/mpasli/mpas.gis1to10km/
(on Anvil that's at `/lcrc/group/acme/public_html/inputdata/glc/mpasli/mpas.gis1to10km`)

Let me know if you have any trouble with that.  Also, just to check, the mesh itself didn't change from the previous version, right?  Just the values of the initial condition fields?  (If the mesh changes at all then we need new graph and mapping files, but presumably you would have run into that already if that was the case.)

2021-12-10 15:54 UTC, matthewhoffman commented
@jonbob, Can you give this a quick lookover before I merge it?  Once that happens, I'll immediately open a PR in E3SM-Project/E3SM for merging our whole MALI dev branch back in. 

One final question for @stephenprice and @jonbob : Do we have any tests that use either the low or high res GIS meshes?  Do we want to add any (or update them) in this PR?

2021-12-10 16:03 UTC, matthewhoffman commented
@stephenprice , one other thing.  I looked at the updated 20km mesh, and I think we should fix a couple more things with it as long as we are messing with it.  I think we should interpolate the 1km mu and temperatures fields to the 20km mesh.  I still have reservations about using a mu estimated from driving stress when we can very easily interpolate from the more realistic 1km optimization result.  And I didn't realize it before, but the temperature field in the 20km mesh is total garbage (0 everywhere in 3 dimensions but with random stippling of -8 values in part of the mesh, but it also needs to be in Kelvin, so I'm surprised it's not killing the solver).  We can also easily interpolate the temperature from the 1km mesh that has Mauro's temperature solution on it.  I'm happy to walk you through how to do that, or I'm sure we can rope @trhille into doing it next week. :)

2021-12-10 18:20 UTC, stephenprice commented on components/mpas-albany-landice/cime_config/buildnml
> +        grid_date += '20210824'
@matthewhoffman -- that file is there as far as I can tell:

`/lcrc/group/e3sm/public_html/inputdata/glc/mpasli/mpas.gis1to10km/gis_1to10km_r01.20210824.nc`

Note that in this PR, it gets a new prefix, `gis_1to10km_r01`. 

The mesh did not change and the graph files still work (as confirmed by tests on Cori using this new init. cond.).

2021-12-10 18:22 UTC, stephenprice commented
@matthewhoffman, @jonbob -- At some point, we had a test in place for the 20km GIS mesh (part of the reason we are updating that file w/ this PR -- the old input file should fail w/ the code updates in this PR) but I don't know much more about it than that.

2021-12-10 18:23 UTC, stephenprice commented
@matthewhoffman - if you want to give me a few brief pointers on slack, r.e. interpolating 1km beta onto the 20km mesh, I'm happy to work on that too. Thanks.

2021-12-13 20:25 UTC, jonbob commented
@matthewhoffman -- it all looks good to me. The only tests in the automated suites that I can find are these:
* SMS.ne30_oECv3_gis.IGELM_MLI.elm-extrasnowlayers
* ERS.f09_g16_g.MALISIA
* SMS.T62_oQU120_ais20.MPAS_LISIO_TEST
* SMS.f09_g16_a.IGELM_MLI
I think we're more-or-less stuck testing limited MALI options just because Albany isn't yet installed on any of the testing platforms? That said, we can still update these tests to reflect v2 configurations, either as part of this PR or in a full-up one

2021-12-14 23:51 UTC, stephenprice commented
The init. cond. files for the 20km and 1to10km meshes should both be in good shape now.

- muFriction for the 1to10km file was multiplied by 1000 (relative to prev. value)
- effective pressure was set to 1 everywhere
- for the 20km file, muFriction was interpolated from the 1to10km file

In test runs for each (~10 days) on Cori, the files were pulled down from the repo on Anvil and ran successfully. Below are the sfc vel. fields for both the 20km (left) and 1to10km (right) in m/yr. 

![Screen Shot 2021-12-14 at 4 49 06 PM](https://user-images.githubusercontent.com/4983771/146097453-9dac9431-e2de-48f5-a29c-f9163f02a7b1.png)

2021-12-15 00:06 UTC, mperego approved these changes
That's great. Tahnks @stephenprice !

2022-01-05 21:48 UTC, merged

2022-01-05 21:49 UTC, matthewhoffman reviewed
Changes look good - merging.

2022-01-18 21:33 UTC, matthewhoffman commented on cime_config/machines/cmake_macros/intel_cori-haswell.cmake
> -string(APPEND FFLAGS " -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model consistent -fimf-use-svml")
@stephenprice , was this deletion intentional?  @jonbob noticed it in reviewing https://github.com/E3SM-Project/E3SM/pull/4725#discussion_r787117607

2022-01-19 19:54 UTC, mperego commented on cime_config/machines/cmake_macros/intel_cori-haswell.cmake
> -string(APPEND FFLAGS " -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model consistent -fimf-use-svml")
Yeah, I think @jonbob is right. We did not intend to remove the second line ("string(APPEND.."). We only wanted to remove the line with the ALBANY_PATH.

2022-01-19 22:04 UTC, matthewhoffman commented on cime_config/machines/cmake_macros/intel_cori-haswell.cmake
> -string(APPEND FFLAGS " -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model consistent -fimf-use-svml")
Thanks, @mperego and @stephenprice .  @jonbob , I will merge a correction this afternoon and update the E3SM PR.