Add spatially variable von Mises threshold stress
MALI-Dev/E3SM pull request #25
Opened 2022-04-05 03:42 UTC by trhille

Add the ability to have the von Mises threshold stress for grounded and floating ice read in from input files. Add config options `config_grounded_von_Mises_threshold_stress_source` and `config_floating_von_Mises_threshold_stress_source` which are set  to `'data'` if the spatially varying field is to be red from an input file, and to `'scalar'` if it is to be set by `config_grounded_von_Mises_threshold_stress` and `config_grounded_von_Mises_threshold_stress`.

2022-04-06 15:48 UTC, trhille commented
I tested this on the circular shelf domain, using a prescribed radially symmetric velocity field and a two-valued `floatingVonMisesThresholdStress` field (`groundedVonMisesThresholdStress` was set equal to `floatingVonMisesThresholdStress`, but there was no grounded ice in the domain). The test exhibited the expected behavior.
![image](https://user-images.githubusercontent.com/17446278/162015105-4f331e79-6f3b-4da7-9389-78eb459e790a.png)
![image](https://user-images.githubusercontent.com/17446278/162015146-f1ec9077-3253-4423-8249-17eda9f628ce.png)
![image](https://user-images.githubusercontent.com/17446278/162015170-db335c0d-53bc-498c-b336-9459cc2dfa6d.png)
![image](https://user-images.githubusercontent.com/17446278/162015228-81fc2d9e-f770-41c8-b0de-6f674415a33f.png)
![image](https://user-images.githubusercontent.com/17446278/162015262-d0a87148-6ea3-4832-9bbd-ea610bfb9197.png)

2022-04-12 20:30 UTC, matthewhoffman requested changes
@trhille , thanks for adding this functionality that is clearly going to be needed for realistic whole-ice-sheet runs.  I requested a few picky changes.

2022-04-12 20:30 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +      if ( config_floating_von_Mises_threshold_stress < 0.0_RKIND ) then
Let's move these two checks into the if-statements below on lines 1610-1629.  I.e., we only check for valid values of the namelist parameter if we are actually using them.

2022-04-12 20:30 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                ! do nothing - use value from input file
Maybe we should check that the provided fields have valid values (>0 or >=0), like we do for the scalars.

2022-04-12 20:30 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="groundedVonMisesThresholdStress"/>
It's a little clunky to require these two fields in every restart file, even if the von Mises calving law isn't operational.  But we are already requiring that for the eigencalvingParameter (which we almost never use...), so it's not a terrible change to add.  I think the only way around this to make packages for each and make these entries package-dependent.  That's kind of a pain, but can you add a comment here saying we should do that if restart file sizes become too large?

2022-04-12 20:30 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="groundedVonMisesThresholdStress"/>
It's a little clunky to require these two fields in every restart file, even if the von Mises calving law isn't operational.  But we are already requiring that for the eigencalvingParameter (which we almost never use...), so it's not a terrible change to add.  I think the only way around this to make packages for each and make these entries package-dependent.  That's kind of a pain, but can you add a comment here saying we should do that if restart file sizes become too large?

2022-04-12 21:58 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                ! do nothing - use value from input file
Addressed in https://github.com/MALI-Dev/E3SM/pull/25/commits/e21abe7eb32b9a4f5bd74e8081fcc68e7b9192fc

2022-04-12 21:58 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +      if ( config_floating_von_Mises_threshold_stress < 0.0_RKIND ) then
Addressed in https://github.com/MALI-Dev/E3SM/pull/25/commits/e21abe7eb32b9a4f5bd74e8081fcc68e7b9192fc

2022-04-14 20:25 UTC, matthewhoffman approved these changes

2022-04-14 21:01 UTC, merged

2022-04-14 21:02 UTC, matthewhoffman commented
All tests in `full_integration` suite pass.  None of them test these routines, but your testing is sufficient for demonstrating the new functionality.