Add SMB mask for bareland
MALI-Dev/E3SM pull request #26
Opened 2022-04-07 00:03 UTC by hollyhan

This PR
1) adds a mask for the applied SMB field such that `sfcMassBal=0` in bareland regions 
and adds a config option for utilizing the SMB mask.
2) modifies the condition statement for checking ice-free ocean cells.

2022-04-07 22:59 UTC, trhille requested changes

2022-04-07 22:59 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +        <nml_option name="config_smbMask" type="logical" default_value=".false." units="unitless"
It would be good to have a more descriptive name for this option. I'd propose something like `config_zero_sfcMassBalApplied_outside_ice_mask` or `config_zero_sfcMassBalApplied_over_bare_land`.

2022-04-07 22:59 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +                    description="Mask to zero out applied SMB in regions where there is no ice at the timestep."
Change "applied SMB" to sfcMassBalApplied. It would also be helpful to have a sentence describing why this setting would be used.

2022-04-07 22:59 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +             bedTopography(iCell) <= config_sea_level .and. .not.(li_mask_is_ice(cellMask(iCell)) ) ) then
I don't see a problem with this, but why is this change necessary?

2022-04-07 22:59 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                bedTopography(iCell) > config_sea_level .and. .not.(li_mask_is_ice(cellMask(iCell)) ) ) then
If running a coupled MALI-SLM simulation, will this behave as expected? I don't know how bedTopography and config_sea_level are treated in that case.

2022-04-07 23:02 UTC, trhille commented
I tested this on Badger using ais8-80km_100yr_spinup_20220317.nc, setting `sfcMassBal` to 1 m/yr everywhere thickness == 0.0 in the input file. I'm seeing the expected the behavior.  Below, white contour is cellMask_ice == 1, cyan is cellMask_initialExtent == 1, black contour is bedTopography == 0. So, we are seeing that `sfcMassBal` is zero outside the ice mask and is positive when ice is advected beyond the initial ice margin.

![image](https://user-images.githubusercontent.com/17446278/162333191-fda9b6d1-13b2-4039-adfa-41d9cc261740.png)

2022-04-12 20:40 UTC, matthewhoffman requested changes
@hollyhan , thanks for getting this feature implemented.  I made a few small requests, and I also agree with the feedback Trevor added.

2022-04-12 20:40 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +         call mpas_pool_get_config(liConfigs, 'config_smbMask', config_smbMask)
Move this before the `iCell` loop, because it only needs to be evaluated once.

2022-04-12 20:40 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +        <nml_option name="config_smbMask" type="logical" default_value=".false." units="unitless"
I agree we should use a different name.  In general, config options use underscores instead of camel case, and we want a more descriptive name.  I think `config_zero_sfcMassBalApplied_over_bare_land` works.  Another option could be `config_allow_glacial_inception`, but I think `config_zero_sfcMassBalApplied_over_bare_land` is clearer.

Also, if my memory is correct, we decided to make this true by default - we anticipate always wanting to use this for realistic cases.  (If we do that, we will need to add this option with a false value to a number of our idealized test cases in COMPASS, but that's ok.)

2022-04-13 19:33 UTC, hollyhan commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +             bedTopography(iCell) <= config_sea_level .and. .not.(li_mask_is_ice(cellMask(iCell)) ) ) then
We initially thought that the definition of open ocean would include the sea surface height that we define `config_sea_level`.  But now that I think about it again, it would make more sense (given that it's imperfect either way) to not make this change because zero sea level `config_sea_level=0` actually (at least in the sea-level theory/modeling) represent the bounding surface between bedTopography and ocean, and thus should include both surfaces for example on the interface of ocean and land. I can change this back to the original version. What do you think, @matthewhoffman?

2022-04-13 19:42 UTC, hollyhan commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                bedTopography(iCell) > config_sea_level .and. .not.(li_mask_is_ice(cellMask(iCell)) ) ) then
@trhille. Since update in `bedTopography` will happen by simply adding the changes in `bedTopography` calculated by the SLM to that from the previous coupling time step, I think there won't be any breaks or unexpected issues with this change in coupled simulations, but only as long as `config_sea_level` is set to zero to maintain the consistence of definition of `bedTopography` and sea level across MALI and SLM.

2022-04-13 23:50 UTC, hollyhan commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +             bedTopography(iCell) <= config_sea_level .and. .not.(li_mask_is_ice(cellMask(iCell)) ) ) then
@trhille, I had a chat with @matthewhoffman about this and we decided to revert this change to the original state of this part, but instead include the zero surface to bedTopography field. The decision is based on the fact that we want to be consistent with the setup that already exists in the `eismint2` test case in compass [https://github.com/MPAS-Dev/compass/blob/master/compass/landice/tests/eismint2/run_experiment.py#L219] To reflect this decision on this PR, I'm going make a change in Line 787 from `bedTopography(iCell)  > config_sea_level...` to `bedTopography(iCell)  >= config_sea_level...`.

2022-04-14 00:09 UTC, hollyhan commented
PR updated - @trhille & @matthewhoffman ! :)

2022-04-14 18:29 UTC, matthewhoffman commented
I tested this with COMPASS and got the following failures:
```
Test Runtimes:
00:23 PASS landice_dome_2000m_sia_restart_test
00:08 PASS landice_dome_2000m_sia_decomposition_test
00:09 PASS landice_dome_variable_resolution_sia_restart_test
00:06 PASS landice_dome_variable_resolution_sia_decomposition_test
00:34 PASS landice_enthalpy_benchmark_A
01:14 FAIL landice_eismint2_decomposition_test
00:24 FAIL landice_eismint2_enthalpy_decomposition_test
00:29 FAIL landice_eismint2_restart_test
00:29 FAIL landice_eismint2_enthalpy_restart_test
00:27 FAIL landice_greenland_sia_restart_test
00:19 FAIL landice_greenland_sia_decomposition_test
00:12 PASS landice_hydro_radial_restart_test
00:07 PASS landice_hydro_radial_decomposition_test
00:18 PASS landice_dome_2000m_fo_decomposition_test
00:17 PASS landice_dome_2000m_fo_restart_test
00:11 PASS landice_dome_variable_resolution_fo_decomposition_test
00:13 PASS landice_dome_variable_resolution_fo_restart_test
00:14 PASS landice_circular_shelf_decomposition_test
00:41 FAIL landice_greenland_fo_decomposition_test
00:42 FAIL landice_greenland_fo_restart_test
00:33 PASS landice_thwaites_decomposition_test
00:46 PASS landice_thwaites_restart_test
Total runtime 08:58
FAIL: 8 tests failed, see above.
```

I think these are all expected.  Based on the changes in this PR, I expect we need to modify the EISMINT tests to add `config_zero_sfcMassBalApplied_over_bare_land = .false.`.  I will create a COMPASS PR to update those tests.  The greenland failures are because the default treatment of SMB over bare land has changed.  We could restore the old behavior and get BFB results if we set the new option to false for the greenland tests.  But in the greenland case, I think we do want the new behavior, so I will bless those diffs.

2022-04-14 18:37 UTC, merged