Distribute unablatedVolumeDynCell among neighboring cells
MALI-Dev/E3SM pull request #27
Opened 2022-04-11 21:34 UTC by trhille

If a cell is left with unablated volume after step 2c in li_apply_front_ablation_velocity, distribute that volume among its dynamic neighbors to prevent large errors in the ablated volume. Testing with von Mises calving on the MISMIP+ domain indicates that this greatly reduces inaccuracies in the calving routine, but that very large calving events can still trigger the >10% calving inaccuracy error. This could potentially be alleviated by adding a do-while loop over the new section 3 in li_apply_front_ablation_velocity, but we may want to control for extremely large calving events anyway.

2022-04-11 23:18 UTC, trhille commented
Test with `config_velocity_solver = 'none'`, von Mises threshold stresses of 35 kPa on spun up MISMIP+ domain, with specified `uReconstructY = 0.0` and `uReconstructX = xCell / 1.0e10` (which gives a similar velocity to diagnostic solve at calving front.):
![image](https://user-images.githubusercontent.com/17446278/162848305-6aae6c76-1b79-4b2f-bb9c-b9ddd42d14b4.png)
![image](https://user-images.githubusercontent.com/17446278/162848347-4a4eaa3a-19b7-49e4-8603-5cb41d1f4ecb.png)
![image](https://user-images.githubusercontent.com/17446278/162848375-0eea81f6-fc67-4648-8e6f-ec8d1469ea96.png)
![image](https://user-images.githubusercontent.com/17446278/162848397-efb042ce-ab9b-426f-9a43-8ae8472f8e61.png)
![image](https://user-images.githubusercontent.com/17446278/162848423-197a5043-6e32-4834-a5d1-e8597baea848.png)

2022-04-11 23:34 UTC, trhille commented
Testing with `config_velocity_solver = 'FO'` on the same domain (without specified velocities), von Mises thresholds of 35 kPa. Using this branch, it ran 138 timesteps (60 years) and printed 50 `WARNING: Failed to ablate` messages before the error exceeded 10%. Using an exe compiled on the head of `MALI-Dev/develop`, it ran for 58 timesteps (30 years), with 55 `WARNING: Failed to ablate` messages before breaking the 10% threshold.

In the screenshots below, the top panel is from the run using this branch and bottom is from `MALI-Dev/develop`:
![image](https://user-images.githubusercontent.com/17446278/162849719-6a6451b3-ef65-4625-ac92-8ba419b56f72.png)
![image](https://user-images.githubusercontent.com/17446278/162849738-f619e115-49b4-4b93-969f-0828836cb367.png)
![image](https://user-images.githubusercontent.com/17446278/162849767-a76f073b-1de8-4678-8906-ed0a6d52cbfd.png)

Continuing run on this branch after the `MALI-Dev/develop` run failed:
![image](https://user-images.githubusercontent.com/17446278/162849835-8247fd41-89fd-43c3-8caa-bde99d070275.png)
![image](https://user-images.githubusercontent.com/17446278/162849852-d73335c7-cac7-4b8c-a3c7-137f1f2c6881.png)

2022-04-11 23:46 UTC, trhille commented
Testing the effect of `config_max_adaptive_timestep`. I ran the same cases (35 kPa von Mises calving threshold, active velocity solver, MISMIP+ domain), setting config_max_adaptive_timestep to 180, 60, and 20 days on both this branch and `MALI-dev/develop`.
180 day maximum timestep:
- develop: 72 timesteps, 34 years, 68 calving warning messages before encountering >10% error
- this branch: 80 timesteps, 37 years, 16 calving warning messages, timed out without encountering >10% error

60 and 20 day maximum timesteps encountered no "Failed to ablate" warnings on either branch. I will try with larger values and update this soon.

2022-04-12 20:15 UTC, trhille commented
Note that results are not currently bit-for-bit across different numbers of processors. I tested the `Humboldt_1to10km_r04_20210615.nc` domain on Badger on 5 nodes (180 procs) and 2 nodes (72 procs) and compared with the same run from my Humboldt paper. This is using q=1/5, von Mises threshold of 160 kPa, and the 20 m/yr subshelf melt tuning.
Below, Green is the run on Cori that went into the Humboldt paper; orange is the run using 2 nodes and this branch on Badger; blue is using 5 nodes and this branch on Badger. The 5 node run _did_ encounter the >10% calving error in 2093, while the 2 node run did not. The previous run from the Humboldt paper first encountered this error in 2078, judging from `config_max_adaptive_timestep` settings in restart files, so this is still an improvement.

![image](https://user-images.githubusercontent.com/17446278/163045638-caab2d3c-62de-4a5e-9dab-b20226e0100a.png)

2022-04-12 20:18 UTC, matthewhoffman commented
@trhille , recap of our discussion today about this PR:
* We could consider adding an iteration look for this new functionality that can be namelist-configurable to allow for 0 iterations (old behavior), 1 iteration (current behavior ), or many iterations.
* Ideally we would make this behavior work BFB on different decompositions and/or global indexing order.

2022-04-12 21:28 UTC, matthewhoffman requested changes
I made some minor suggestions.  I don't think they will significantly affect the behavior.

2022-04-12 21:28 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                    .and. (cellVolume(iNeighbor) > 0.0_RKIND) ) then
Better to have a tolerance than  using 0.0 here.

2022-04-12 21:28 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +               .and. (cellVolume(iCell) > 0.0_RKIND) )then
Let's add a condition for `unablatedVolumeDynCell(iCell))>0.0_RKIND` here to avoid performing these calculations for vast swaths of the ice shelf / marine ice sheet.

2022-04-12 21:28 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +               if (iCell <= nCellsSolve) ablationSubtotal2 = ablationSubtotal2 + removeVolumeHere
I could imagine we might want an additional metric for this particular step, but it's probably fine to leave as is unless we need more information for debugging.

2022-04-12 21:28 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +      integer :: err_tmp, iter, nDynNeighbors
`iter` is not currently used.

2022-04-12 22:51 UTC, trhille commented
Still testing on commit b92225d before addressing @matthewhoffman's comments. I tested the MISMIP case with the imposed velocity field as before, using 36 and 72 procs. These are close, but not bit-for-bit, indicating that more work is needed. but there is an unsettling feature in the calving flux:
![image](https://user-images.githubusercontent.com/17446278/163067208-93fd60fc-bcc2-4921-9129-3fd59fec77c9.png)
zoomed in:
![image](https://user-images.githubusercontent.com/17446278/163067237-cab059e6-d6cd-41bb-9e1e-84ad6e761104.png)

Both the restart file output interval and `config_adaptive_timestep_force_interval` are set to years, which is the interval at which those negative excursions occur regularly in the calvingFlux plot. But neither of those should effect this. Why is this happening? Will test further by changing `config_adaptive_timestep_force_interval` and see if this tracks it, then likewise with restart interval.

2022-04-12 23:30 UTC, trhille commented
Reducing `config_adaptive_timestep_force_interval` to 5 years instead of 10 also causes those negative spikes to occur every five years (here using 36 procs):
![image](https://user-images.githubusercontent.com/17446278/163070871-7e1a2c68-0ad0-4c99-8872-38cd754a63f3.png)

2022-04-12 23:49 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                    .and. (cellVolume(iNeighbor) > 0.0_RKIND) ) then
Why is that? This is an inequality and requires a dynamic cell, so setting a tolerance does not seem like it would be helpful to me, and would at any rate be pretty arbitrary.

2022-04-13 00:03 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                    .and. (cellVolume(iNeighbor) > 0.0_RKIND) ) then
It's not clear to me what that tolerance should be. Should it be something like `1 m thickness * areaCell(iNeighbor)`, some fraction of `unablatedVolumeDynCell(iCell)`, or something else?

2022-04-13 00:17 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +               .and. (cellVolume(iCell) > 0.0_RKIND) )then
Added in commit d8d4de36feb15cd7b77a227e4ad64df84117ba17

2022-04-13 00:17 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +               if (iCell <= nCellsSolve) ablationSubtotal2 = ablationSubtotal2 + removeVolumeHere
Added a comment mentioning this in commit d8d4de36feb15cd7b77a227e4ad64df84117ba17

2022-04-13 00:17 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +      integer :: err_tmp, iter, nDynNeighbors
Removed in commit d8d4de36feb15cd7b77a227e4ad64df84117ba17.

2022-04-13 00:46 UTC, trhille commented
These same runs using `MALI-Dev/develop` with velocity solver turned off on 36 and 72 procs are also not bit-for-bit, so that issue does not seem to stem from this PR:
![image](https://user-images.githubusercontent.com/17446278/163077248-1e547b28-99e9-4b97-8add-cacb7586a727.png)

2022-04-13 19:16 UTC, trhille commented
I tested this using @matthewhoffman's calving test suite in https://github.com/MPAS-Dev/compass/pull/318 and rebasing onto the branch in https://github.com/MALI-Dev/E3SM/pull/28. The changes here give bit-for-bit results across different numbers of processors when the changes in PR #28 are included:
```
Test Runtimes:
01:18 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-none
01:05 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-floating
01:04 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-eigencalving
01:04 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-specified_calving_velocity
01:03 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-von_mises_stress
01:04 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-damagecalving
01:05 FAIL landice_humboldt_mesh-default_decomposition_test_velo-none_calving-ismip6_retreat
00:23 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-none
00:23 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-floating
00:21 FAIL landice_humboldt_mesh-default_restart_test_velo-none_calving-eigencalving
00:24 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-specified_calving_velocity
00:23 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-von_mises_stress
00:23 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-damagecalving
00:24 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-ismip6_retreat
Total runtime 10:27
FAIL: 2 tests failed, see above.
```

For references, here are the test results using `MALI-Dev/develop`:
```
Test Runtimes:
01:01 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-none
01:02 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-floating
01:02 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-eigencalving
01:02 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-specified_calving_velocity
01:02 FAIL landice_humboldt_mesh-default_decomposition_test_velo-none_calving-von_mises_stress
01:02 PASS landice_humboldt_mesh-default_decomposition_test_velo-none_calving-damagecalving
01:03 FAIL landice_humboldt_mesh-default_decomposition_test_velo-none_calving-ismip6_retreat
00:22 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-none
00:22 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-floating
00:20 FAIL landice_humboldt_mesh-default_restart_test_velo-none_calving-eigencalving
00:23 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-specified_calving_velocity
00:22 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-von_mises_stress
00:22 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-damagecalving
00:23 PASS landice_humboldt_mesh-default_restart_test_velo-none_calving-ismip6_retreat
Total runtime 09:48
FAIL: 3 tests failed, see above.
```
Note that I had to change `config_calving_eigencalving_parameter_scalar_value` from 3.14e16 to 3.14e14 to avoid the >10% failed ablation error, but that error still occurs in the restart test. This is strange, but not within the scope of this PR.

2022-04-14 21:27 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                    .and. (cellVolume(iNeighbor) > 0.0_RKIND) ) then
I was imagining an `eps` or `tol` variable with a value of 1.0e-6 or something.  The goal being just to catch round off level errors.

2022-04-18 20:46 UTC, trhille commented
Force-push from d8d4de3 to a4cfdad is a rebase onto MALI-Dev/develop at commit 8df83d92551b5dad20d71674ad850ef1b95ed618

2022-04-20 19:57 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                    .and. (cellVolume(iNeighbor) > 0.0_RKIND) ) then
This was addressed in commit https://github.com/MALI-Dev/E3SM/commit/9202029b413eeb11c645765e3b035bb58769563f.

2022-04-29 21:49 UTC, matthewhoffman commented
I rested full_integration suite against current baseline, and all tests pass:
```
Test Runtimes:
00:09 PASS landice_dome_2000m_sia_restart_test
00:06 PASS landice_dome_2000m_sia_decomposition_test
00:07 PASS landice_dome_variable_resolution_sia_restart_test
00:04 PASS landice_dome_variable_resolution_sia_decomposition_test
00:31 PASS landice_enthalpy_benchmark_A
00:12 PASS landice_eismint2_decomposition_test
00:12 PASS landice_eismint2_enthalpy_decomposition_test
00:13 PASS landice_eismint2_restart_test
00:13 PASS landice_eismint2_enthalpy_restart_test
00:16 PASS landice_greenland_sia_restart_test
00:09 PASS landice_greenland_sia_decomposition_test
00:08 PASS landice_hydro_radial_restart_test
00:06 PASS landice_hydro_radial_decomposition_test
00:17 PASS landice_dome_2000m_fo_decomposition_test
00:15 PASS landice_dome_2000m_fo_restart_test
00:10 PASS landice_dome_variable_resolution_fo_decomposition_test
00:11 PASS landice_dome_variable_resolution_fo_restart_test
00:13 PASS landice_circular_shelf_decomposition_test
00:40 PASS landice_greenland_fo_decomposition_test
00:41 PASS landice_greenland_fo_restart_test
00:32 PASS landice_thwaites_decomposition_test
00:43 PASS landice_thwaites_restart_test
00:50 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 07:01
PASS: All passed successfully!
```

I also tested the humboldt_calving_tests suite (without a baseline), and all tests pass except the one that was already failing:
```
Test Runtimes:
00:11 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-none
00:12 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-floating
00:11 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-eigencalving
00:11 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-specified_calving_velocity
00:12 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-von_mises_stress
00:11 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-damagecalving
00:12 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-ismip6_retreat
00:12 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-von_mises_stress_damage-threshold_faceMelting
00:17 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-none
00:17 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-floating
00:17 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-eigencalving
00:18 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-specified_calving_velocity
00:17 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-von_mises_stress
00:17 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-damagecalving
00:18 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-ismip6_retreat
00:18 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 03:52
FAIL: 1 test failed, see above.
```

It is likely that none of these tests exercise the new code, because if they did, they probably would have been generating runtime errors before this.  That said, I confirm this code does no harm.  

@trhille's initial testing above on custom cases where the calving inaccuracy occurs look solid.  More careful testing will be done in conjunction with testing for #33 .  Any issues that come up can be revisited then (including if we want this on by default).

2022-04-29 21:49 UTC, merged

2022-04-29 21:50 UTC, matthewhoffman approved these changes