Add applied basal mass balance fields
MALI-Dev/E3SM pull request #31
Opened 2022-04-21 15:16 UTC by trhille

Add applied basal mass balance fields, in which the calculated and prescribed basal mass balance is limited by the ice thickness. This addresses the problems recorded in https://github.com/MALI-Dev/E3SM/issues/22.

2022-04-21 15:17 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> -		                config_zero_sfcMassBalApplied_over_bare_land)
This was a tabbed indent instead of spaces.

2022-04-21 16:54 UTC, trhille commented
Passes all baseline comparisons:
```
Test Runtimes:
00:07 PASS landice_dome_2000m_sia_restart_test
00:05 PASS landice_dome_2000m_sia_decomposition_test
00:07 PASS landice_dome_variable_resolution_sia_restart_test
00:04 PASS landice_dome_variable_resolution_sia_decomposition_test
00:31 PASS landice_enthalpy_benchmark_A
00:13 PASS landice_eismint2_decomposition_test
00:13 PASS landice_eismint2_enthalpy_decomposition_test
00:12 PASS landice_eismint2_restart_test
00:13 PASS landice_eismint2_enthalpy_restart_test
00:16 PASS landice_greenland_sia_restart_test
00:11 PASS landice_greenland_sia_decomposition_test
00:09 PASS landice_hydro_radial_restart_test
00:06 PASS landice_hydro_radial_decomposition_test
00:15 PASS landice_dome_2000m_fo_decomposition_test
00:15 PASS landice_dome_2000m_fo_restart_test
00:10 PASS landice_dome_variable_resolution_fo_decomposition_test
00:12 PASS landice_dome_variable_resolution_fo_restart_test
00:14 PASS landice_circular_shelf_decomposition_test
00:40 PASS landice_greenland_fo_decomposition_test
00:39 PASS landice_greenland_fo_restart_test
00:32 PASS landice_thwaites_decomposition_test
00:43 PASS landice_thwaites_restart_test
Total runtime 06:09
PASS: All passed successfully!
```

2022-04-21 18:01 UTC, trhille commented
Passed all baseline comparisons:
```
Test Runtimes:
00:08 PASS landice_dome_2000m_sia_restart_test
00:05 PASS landice_dome_2000m_sia_decomposition_test
00:07 PASS landice_dome_variable_resolution_sia_restart_test
00:05 PASS landice_dome_variable_resolution_sia_decomposition_test
00:31 PASS landice_enthalpy_benchmark_A
00:15 PASS landice_eismint2_decomposition_test
00:15 PASS landice_eismint2_enthalpy_decomposition_test
00:14 PASS landice_eismint2_restart_test
00:14 PASS landice_eismint2_enthalpy_restart_test
00:18 PASS landice_greenland_sia_restart_test
00:11 PASS landice_greenland_sia_decomposition_test
00:10 PASS landice_hydro_radial_restart_test
00:06 PASS landice_hydro_radial_decomposition_test
00:16 PASS landice_dome_2000m_fo_decomposition_test
00:16 PASS landice_dome_2000m_fo_restart_test
00:11 PASS landice_dome_variable_resolution_fo_decomposition_test
00:12 PASS landice_dome_variable_resolution_fo_restart_test
00:14 PASS landice_circular_shelf_decomposition_test
00:41 PASS landice_greenland_fo_decomposition_test
00:40 PASS landice_greenland_fo_restart_test
00:33 PASS landice_thwaites_decomposition_test
00:43 PASS landice_thwaites_restart_test
Total runtime 06:29
PASS: All passed successfully!
```

2022-04-25 19:00 UTC, matthewhoffman requested changes
See long inline comment.

2022-04-25 19:00 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
>              !TODO - If remaining basalAblat > 0, then keep track of it to conserve energy
@trhille , thanks for tackling this small but intricate issue.  I had to look over this module about four times, but I think I follow all the steps now.  I think here is actually where we want to make the `basalMassBalApplied` adjustment, following the logic used for SMB at line 849 above.  (That's 849 in the current version of the file - the line that reads `! Adjust applied SMB to only be the amount actually applied above (this will include ice-free cells)`)  It needs to happen here to catch the case of SMB **and** BMB contributing to complete removal of ice from a cell.  (And similarly, if SMB adds ice to the cell, a massive BMB would be able to remove the original thickness **plus** any new accumulation from SMB.) As written, SMB would get to remove ice first, which is totally arbitrary, but I think that's fine and maybe slightly preferable if I had to choose.

The one catch to moving it here is that it becomes harder to keep track of the grounded and floating portions of the `Applied` version.  The best way I can think to deal with that is to combine grounded and floating as was done before this PR, do the limiting by ice thickness here, and then after the call to `apply_mass_balance` use the grounded and floating masks to partition it back out.  (Alternatively, the combining and repartitioning could be moved into this routine - either way.). 

There might be other solutions than what I've proposed here, so we can discuss more if you see other options are flaws in my suggestion.

2022-04-28 20:34 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
>              !TODO - If remaining basalAblat > 0, then keep track of it to conserve energy
Thanks @matthewhoffman. I addressed this in https://github.com/MALI-Dev/E3SM/pull/31/commits/cc5e8d9cc4bf1cf3be4c60905e849fb8e24e245c

2022-04-28 20:49 UTC, trhille commented
At commit https://github.com/MALI-Dev/E3SM/pull/31/commits/cc5e8d9cc4bf1cf3be4c60905e849fb8e24e245c, passed all baseline comparisons:
```
Test Runtimes:
00:09 PASS landice_dome_2000m_sia_restart_test
00:06 PASS landice_dome_2000m_sia_decomposition_test
00:08 PASS landice_dome_variable_resolution_sia_restart_test
00:06 PASS landice_dome_variable_resolution_sia_decomposition_test
00:33 PASS landice_enthalpy_benchmark_A
00:15 PASS landice_eismint2_decomposition_test
00:15 PASS landice_eismint2_enthalpy_decomposition_test
00:16 PASS landice_eismint2_restart_test
00:16 PASS landice_eismint2_enthalpy_restart_test
00:19 PASS landice_greenland_sia_restart_test
00:11 PASS landice_greenland_sia_decomposition_test
00:11 PASS landice_hydro_radial_restart_test
00:07 PASS landice_hydro_radial_decomposition_test
00:16 PASS landice_dome_2000m_fo_decomposition_test
00:16 PASS landice_dome_2000m_fo_restart_test
00:12 PASS landice_dome_variable_resolution_fo_decomposition_test
00:13 PASS landice_dome_variable_resolution_fo_restart_test
00:14 PASS landice_circular_shelf_decomposition_test
00:42 PASS landice_greenland_fo_decomposition_test
00:42 PASS landice_greenland_fo_restart_test
00:32 PASS landice_thwaites_decomposition_test
00:43 PASS landice_thwaites_restart_test
00:51 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 07:37
PASS: All passed successfully!
```

2022-04-28 21:23 UTC, matthewhoffman reviewed
I'm going to test this a few ways tomorrow, but I don't see any problems by inspection (other than this one comment typo).

2022-04-28 21:23 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +           basalMassBal          !< Iinput: basal mass balance (kg/m^2/s)
```suggestion
           basalMassBal          !< Input: basal mass balance (kg/m^2/s)
```

2022-04-29 21:27 UTC, matthewhoffman commented
I tested by applying very, very large SMB and BMB to the Thwaites mesh and running for a few years without the velocity solver.  I confirmed that the `applied` fields are limited by the available ice thickness and that the SMB gets available ice thickness first.  I also confirmed globalStats gave the desired behavior:

![image](https://user-images.githubusercontent.com/4182034/166071377-5912302e-9202-4c9e-a3df-2adad524904f.png)

2022-04-29 21:28 UTC, matthewhoffman approved these changes

2022-04-29 21:28 UTC, merged