Create a calving CFL limit and apply to adaptive timestepper
MALI-Dev/E3SM pull request #33
Opened 2022-04-27 19:12 UTC by matthewhoffman

There is reason to think it is incorrect to allow calving to remove more
than a whole grid cell in a given timestep - a CFL condition for
calving.  This commit calculates a calving CFL and adds it to the
adaptive timestepper.  It's important to note that the calving CFL is
calculated from the *previous* timestep, because determining the calving
CFL prior to starting the timestep is prohibitively difficult.  That
would require doing advection and other operations to generate the
geometry that the calvingVelocity will be based on just to calculate the
CFL limit, and then going back and actually progressing through the time
step for real once the dt has been set.  So this addition works under
the principle that the calving CFL limit will not change a lot from
timestep to timestep, thus a lagged CFL limit is a useful way to adapt
the timestep.  In initial tests this appears to work for the simple
MISMIP+ test case.

Note that this additional work is required beyond this commit:
* Right now it is only calculated if using the von Mises calving law
* It is not calculated on the initial time
* Restarts are not handled
* There is not yet an option to disable this
* Adjustments may be desired for how the option for what fraction of the
calving CFL to use interacts with the general CFL dt fraction option
* some general clean up may be desired

2022-05-05 22:20 UTC, matthewhoffman commented
Results of full_integration suite:
```
Test Runtimes:
00:10 PASS landice_dome_2000m_sia_restart_test
00:05 PASS landice_dome_2000m_sia_decomposition_test
00:08 PASS landice_dome_variable_resolution_sia_restart_test
00:04 PASS landice_dome_variable_resolution_sia_decomposition_test
00:31 PASS landice_enthalpy_benchmark_A
00:13 PASS landice_eismint2_decomposition_test
00:13 PASS landice_eismint2_enthalpy_decomposition_test
00:14 PASS landice_eismint2_restart_test
00:14 PASS landice_eismint2_enthalpy_restart_test
00:18 FAIL landice_greenland_sia_restart_test
00:09 FAIL landice_greenland_sia_decomposition_test
00:09 PASS landice_hydro_radial_restart_test
00:06 PASS landice_hydro_radial_decomposition_test
00:17 PASS landice_dome_2000m_fo_decomposition_test
00:14 PASS landice_dome_2000m_fo_restart_test
00:11 PASS landice_dome_variable_resolution_fo_decomposition_test
00:13 PASS landice_dome_variable_resolution_fo_restart_test
00:14 PASS landice_circular_shelf_decomposition_test
00:41 FAIL landice_greenland_fo_decomposition_test
00:41 FAIL landice_greenland_fo_restart_test
00:32 PASS landice_thwaites_decomposition_test
00:44 PASS landice_thwaites_restart_test
00:51 FAIL landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 07:14
FAIL: 5 tests failed, see above.
```
The greenland failures are because this PR applies the calving routine on the initial time, whereas before it was not applied until the first time step.  For rate-based calving laws, applying calving on the initial time has no effect because dt=0, but for threshold-based calving laws, this change will apply calving on the initial time.  The greenland cases all are currently using thickness-based calving, so applying calving on the initial time removes floating ice from a handful of grid cells in NE Greenland.  As I mention in the commit messages, I think we actually prefer to have threshold-based calving applied on the initial time, so this change is desireable.

The `landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting` failure is due to a small change (order 1e-6 m/s) to `calvingVelocity` (but not `calvingThickness`).  This PR includes a lot of minor adjustments to how calving is processed, so that level of change did not concern me.

Therefore, I would consider all these changes as blessed.

To actually test this PR, I would run the `calving_dt_convergence` suite in the accompanying COMPASS PR: https://github.com/MPAS-Dev/compass/pull/386

@trhille , you may also want to run one of your Humboldt paper runs to ensure there are no major differences.

2022-05-09 22:21 UTC, trhille commented
I see the same 5 tests failing baseline comparison.
```
Test Runtimes:
00:09 PASS landice_dome_2000m_sia_restart_test
00:05 PASS landice_dome_2000m_sia_decomposition_test
00:08 PASS landice_dome_variable_resolution_sia_restart_test
00:05 PASS landice_dome_variable_resolution_sia_decomposition_test
00:33 PASS landice_enthalpy_benchmark_A
00:12 PASS landice_eismint2_decomposition_test
00:12 PASS landice_eismint2_enthalpy_decomposition_test
00:14 PASS landice_eismint2_restart_test
00:14 PASS landice_eismint2_enthalpy_restart_test
00:18 FAIL landice_greenland_sia_restart_test
00:10 FAIL landice_greenland_sia_decomposition_test
00:09 PASS landice_hydro_radial_restart_test
00:06 PASS landice_hydro_radial_decomposition_test
00:16 PASS landice_dome_2000m_fo_decomposition_test
00:15 PASS landice_dome_2000m_fo_restart_test
00:11 PASS landice_dome_variable_resolution_fo_decomposition_test
00:13 PASS landice_dome_variable_resolution_fo_restart_test
00:14 PASS landice_circular_shelf_decomposition_test
00:41 FAIL landice_greenland_fo_decomposition_test
00:40 FAIL landice_greenland_fo_restart_test
00:32 PASS landice_thwaites_decomposition_test
00:43 PASS landice_thwaites_restart_test
00:51 FAIL landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 07:13
FAIL: 5 tests failed, see above.
```

2022-05-10 15:00 UTC, trhille commented
I also tested this on the Humboldt_1to10km_r04_20210615 mesh using the most aggressive mass loss scenario from the perturbed parameter ensemble in my paper (HadGEM2 climate, 170 kPa von Mises threshold stress, q = 1/7). Happily, these changes result in only minor differences from the original simulation, which used an executable compiled using https://github.com/MALI-Dev/E3SM/tree/d0c286778a6a035c600af891a268ed9f843aac52 and https://github.com/sandialabs/Albany/tree/ecbc0182015fda8d6a2bb29eaa3a47c260f40b13.
In the results below, blue is the run from the original ensemble, green is compiled on the current head of `MALI-Dev/develop` (commit 6c065330c4d7fc3afbbffb8f6e827ce2ad095b7e, with commit 8dcab76ecc4591c8049131b130b06619662650b1 cherry-picked to enable compiling on Cori), and orange was compiled using this branch (also with commit 8dcab76ecc4591c8049131b130b06619662650b1 cherry-picked):
![image](https://user-images.githubusercontent.com/17446278/167659094-5dcdc2ff-5170-4e72-8b08-d638f8c93aba.png)
![image](https://user-images.githubusercontent.com/17446278/167659130-d0ea679e-ac7a-4a2f-a8a3-7c5dd2ac3934.png)
![image](https://user-images.githubusercontent.com/17446278/167659256-9b23ce4d-fba0-4241-ad99-915927dbc48d.png)

2022-05-10 17:12 UTC, trhille requested changes
@matthewhoffman, this is great! I had a few minor suggestions here and there. One concern that could complicate things is that I think we should include face-melting in the CFL condition calculation, although it is unlikely to exceed calving rates.

2022-05-10 17:12 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +         if (unablatedVolumeNonDynCell(iCell) < 1.0e-5_RKIND) then
Here and in the next if-statement, we should use `unablatedVolumeNonDynCell(iCell) < (ablationSmallThk * areaCell(iCell)))` for consistency.

2022-05-10 17:12 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_core.F
> +      ! many calving laws require velocity-related fields, it need to be called
'need' should be 'needs'

2022-05-10 17:12 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_iceshelf_melt.F
> +         err = ior(err, err_tmp)
It seems like face-melting should also use the calving CFL condition. Does that make things messy?

2022-05-10 23:12 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                     !        realArgs=(/requiredAblationVolumeDynEdge(iEdge)/), intArgs=(/iCell, jCell/))
I'm going to leave this out given it's commented but I'll add a comment pointing that out.

2022-05-10 23:20 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_iceshelf_melt.F
> +         err = ior(err, err_tmp)
It could happen if we added an additional Registry variable for it and additional logic in the adaptive timestepper.  From a practical standpoint, do we ever expect that to be large enough to exceed advection and calving rates?

2022-05-10 23:21 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +		<var name="processLimitingTimestep" type="integer" time_levs="1" dimensions="Time" units="none" default_value="0"
Added in e0baf70a09

2022-05-10 23:21 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                <var name="calvingCFLdt" type="real" dimensions="Time" units="s" time_levs="1" default_value="1.0e16"
Added in e0baf70a09

2022-05-10 23:21 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                <var name="dtCalvingCFLratio" type="real" dimensions="Time" units="s" time_levs="1" default_value="0.0"
Fixed in db5dc40c06

2022-05-10 23:22 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                        description="ratio of timestep being used to the maximum timestep calculated for the calving CFL condition"
Fixed in db5dc40c06

2022-05-10 23:22 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +      real (kind=RKIND), optional :: maxDt !< Output: an approximation of the max allowable dt based on a CFL-like condition
fixed in db5dc40c06

2022-05-10 23:22 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +      real (kind=RKIND), optional :: CFLratio !< Output: the ratio of the actual timestep being applied to what maximum allowable
Fixed in db5dc40c06

2022-05-10 23:22 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +                     !        realArgs=(/requiredAblationVolumeDynEdge(iEdge)/), intArgs=(/iCell, jCell/))
Noted in 711476a69a

2022-05-10 23:22 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_calving.F
> +         if (unablatedVolumeNonDynCell(iCell) < 1.0e-5_RKIND) then
Changed in 711476a69a

2022-05-10 23:23 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_core.F
> +      ! many calving laws require velocity-related fields, it need to be called
Fixed in 711476a69a

2022-05-10 23:27 UTC, matthewhoffman commented
@trhille , thanks for the review and the informative testing on this.  I updated the PR.  Let me know if you think we should add the faceMelting CFL limit or not.  I'm inclined to not bother, but I could be convinced.

2022-05-10 23:27 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_iceshelf_melt.F
> +         err = ior(err, err_tmp)
It probably won't happen, but I don't know whether it's safe to assume in all cases. We could add a check here that writes a warning anywhere `faceMeltingSpeed > max(calvingVelocity, sqrt(xvelmean**2 + yvelmean**2)`.
But would we need to add a new variable for this, or could it just use `calvingCFLdt`?

2022-05-10 23:37 UTC, trhille commented
@matthewhoffman, thanks for these changes. I don't think any of them will make a difference, but I'll run `full_integration` again to be sure. 

> @trhille , thanks for the review and the informative testing on this. I updated the PR. Let me know if you think we should add the faceMelting CFL limit or not. I'm inclined to not bother, but I could be convinced.
Let's leave it as-is for now. It's probably true that in the vast majority of cases, face melting will not be the dominant velocity, and for our short-term Antarctic use cases that won't matter. We can add that in another PR if we determine it is necessary.

2022-05-11 16:36 UTC, trhille approved these changes
Okay, I'm seeing the same behavior as before when I run `full_integration`, so this is good to go!

2022-05-11 16:37 UTC, merged