Do not modify floatingBasalMassBal
MALI-Dev/E3SM pull request #43
Opened 2022-07-12 19:24 UTC by trhille

The field floatingBasalMassBal should not be modified based on internal melting because it in an input variable. Instead, assign internal melting to the basalMassBal field instead of to floatingBasalMassBal. This involves moving this reassignment from mpas_li_thermal.F to mpas_li_advection.F before mass balance fields are applied to the ice thickness.

2022-07-14 13:15 UTC, matthewhoffman reviewed
@trhille I had time to take another brief look at this.  I made two comments that I think need further consideration, but I neither approved nor requested changes.  If after looking into those two items you feel comfortable with the solution, feel free to merge while I'm gone.

2022-07-14 13:43 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                  ! calculate a mask to identify ice that is thick enough to be thermally active
Thickness should not have been updated between the thermal solver and here. https://github.com/MALI-Dev/E3SM/blob/develop/components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe.F#L138-L156

2022-07-14 13:44 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_thermal.F
> +         ! to the groundedBasalMassBal array.  If so, then this is added to basalMassBal for floating cells in
Yes, that's a good idea. I will implement it.

2022-09-07 14:34 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                <var name="internalMeltRate" type="real" dimensions="nVertLevels nCells Time" units="kg m^{-2} s^{-1}"
This new commit resolves the complications with how internal melting was handled.  However, the name `internalMeltRate` is a little ambiguous, because in the enthalpy model there is some internal melting that is not included in this variable (the amount needed to fill the maximum water fraction).  I'd prefer to call this new variable something like `drainedInternalMeltRate` or `excessInternalMeltRate`.

2022-10-03 21:48 UTC, trhille commented
Force push from  9794803 to 3ad0947 was a rebase onto MALI-Dev/develop, since this hasn't been touched in a while.

2022-10-04 22:09 UTC, trhille commented
Results from latest round of testing.
Here is `floatingBasalMassBal` after 15 years using  an exe compiled on the head of `MALI-Dev/develop`  (commit 12a1a9b8470fed787cfdb2eb342403b6ae14f211):
![image](https://user-images.githubusercontent.com/17446278/193939011-0772294a-b610-4eae-be56-49e42a8d138b.png)

And here is  `floatingBasalMassBal` after 15 years using  an exe compiled on this branch (commit 3ad09476d9f60c2ff11e2c1e9418efa103771a07):
![image](https://user-images.githubusercontent.com/17446278/193939250-fbef2cf6-59ef-4c71-8a34-7b24a909a36d.png)

Both runs used Rignot melt rates, `config_thermal_solver = 'temperature'`, and `config_restore_calving_front = .true.`.

2022-10-04 22:55 UTC, trhille commented
Same as above, but using enthalpy solver instead of temperature. Let is using `develop`, right is using this branch:
![image](https://user-images.githubusercontent.com/17446278/193945325-b2c204fd-d26d-4902-b422-d1392e31d02b.png)

2022-10-04 22:55 UTC, trhille commented
@matthewhoffman, this is ready for you to review.

2022-10-05 15:09 UTC, trhille commented
@matthewhoffman, it's actually unclear what the root of the problem is. But it happens all of a sudden in a single time step, so I don't think it's a case of gradual accumulation, but rather some kind of instability. This merge just makes sure that instability is not propagated through all time steps.

2022-10-05 15:46 UTC, trhille commented
Oh, and I think it only happens in the cells where `restore_calving_front` is adding 1m thick ice, but I'm not totally sure.

2022-10-05 21:14 UTC, matthewhoffman commented
Oh, that issue with `restore_calving` I bet is fixed by this commit I made Friday: https://github.com/MALI-Dev/E3SM/pull/48/commits/1e35980c81c4fb631351107d009c0a8bc82c2279

I think we still want the changes you have here.  However, COMPASS testing revealed two tests that differ from the baseline (but still pass their respective validation criteria):
`landice_eismint2_enthalpy_decomposition_test`
`landice_eismint2_enthalpy_restart_test`
It makes sense that most tests would be unaffected because this change will only affect runs with enthalpy on and few runs have that option.  However what surprises me is that these runs are affected because they have no floating ice.  I interpreted this PR to have no impact on how drained melt is applied to BMB for grounded ice, but the test results indicate the thickness changes on the second time step by 10^-4 m.  (And then those changes propagate to a number of other fields and grow over time.). Would you also anticipate that this PR should not change grounded BMB?

2022-10-06 02:30 UTC, trhille commented
^accidentally hit the wrong button

2022-10-17 17:29 UTC, matthewhoffman requested changes
@trhille , I found the source of the discrepancy from the baseline tests.  In the original organization, drained melt was disabled by the `config_thermal_calculate_bmb` option, but after these changes, that was no longer the case.  I confirmed that applying that option to the drained internal melt application eliminates the baseline comparison issue.

2022-10-17 17:29 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +         ! to the groundedBasalMassBal array in mpas_li_thermal.F.  If so, then add it to basalMassBal.
```suggestion
         ! It is possible that excess internal melting was computed and assigned
         ! to the drainedInternalMeltRate array in mpas_li_thermal.F.  If so, then add it to basalMassBal.
```

2022-10-17 17:29 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +         do iCell = 1, nCells
This do loop needs to be surrounded by a check of `if (config_thermal_calculate_bmb) then`.
It's debatable if internal melt drainage should be considered under the purview of the `config_thermal_calculate_bmb` option, but I think the answer would be yes.  At any rate that is what was happening before.  We should update that option in Registry to make the explicit.

2022-10-17 19:15 UTC, merged

2022-10-17 19:17 UTC, matthewhoffman reviewed
I pushed a commit that fixes the one issue and tested.  Passes all COMPASS tests.