Bug fixes for evolving calving simulations
MALI-Dev/E3SM pull request #50
Opened 2022-10-14 17:46 UTC by matthewhoffman

This PR includes three small bug fixes for evolving calving simulations:
* fixes a check on vM stress values when using a spatial map of values
* fixes a bug in halo values when using restore_calving.  This would lead to garbage temperature values that could keep the solver from the converging.
* changes the definition of floating dynamic ice to avoid edge cases from appearing that lead to large velocity differences for very small thickness changes due to mask changes.  This requires keeping track of the previous dynamic mask, which changes behavior of a cold start vs. a restart.

2022-10-17 20:21 UTC, trhille requested changes
I just found a typo that is repeated a few times. Otherwise, these changes look good. Still pending testing.

2022-10-19 03:18 UTC, matthewhoffman commented on components/mpas-albany-landice/src/shared/mpas_li_mask.F
> +                do j=1,nEdgesOnCell(i) ! Find height of thickest neighbor
That's what we always have been doing.  (Whether that's the best choice is a different question.) The idea is at an ice shelf terminus you want a cliff, so you only want a cell to be dynamic if it's thick enough to essentially be the same thickness as the cells behind it.  We chose the thinnest, because we don't want a reverse driving stress if this location is a little thicker than it's inland neighbors.

2022-10-19 03:23 UTC, matthewhoffman commented
@trhille , I found the bug that was causing the solver to not converge.  There was a missing line of logic that was failing to set floating ice as dynamic after the first time step.  I'm rather baffled how this wasn't a major issue in the ISMIP6 runs I did last week.  I'll certainly want to redo those test runs after we complete this PR.  

In any case, after that fix, here is the velocity field from before this PR (right) and after (left) for the 4km Thwaites mesh.  The arrows point out where the dynamic mesh is slightly different.  These differences look small (as desired) and reasonable given the change in logic.  This isn't proof the new method is better, but it shows it does not do anything unrealistic for this test case.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/4182034/196589586-66f454f7-9f40-4f10-b8ce-bef206aa6be0.png">

Unfortunately, the 4km Thwaites test is still not passing the restart test, so there is something still off about how restarts work.  I'll look at that tomorrow.

2022-10-19 20:41 UTC, matthewhoffman commented
After most recent commit, COMPASS regression suite is showing:
```
Test Runtimes:
00:09 PASS landice_dome_2000m_sia_restart_test
00:06 PASS landice_dome_2000m_sia_decomposition_test
00:08 PASS landice_dome_variable_resolution_sia_restart_test
00:05 PASS landice_dome_variable_resolution_sia_decomposition_test
00:33 PASS landice_enthalpy_benchmark_A
00:15 PASS landice_eismint2_decomposition_test
00:15 PASS landice_eismint2_enthalpy_decomposition_test
00:17 PASS landice_eismint2_restart_test
00:16 PASS landice_eismint2_enthalpy_restart_test
00:20 FAIL landice_greenland_sia_restart_test
00:11 FAIL landice_greenland_sia_decomposition_test
00:10 PASS landice_hydro_radial_restart_test
00:07 PASS landice_hydro_radial_decomposition_test
00:18 PASS landice_dome_2000m_fo_decomposition_test
00:16 PASS landice_dome_2000m_fo_restart_test
00:15 PASS landice_dome_variable_resolution_fo_decomposition_test
00:13 PASS landice_dome_variable_resolution_fo_restart_test
00:16 PASS landice_circular_shelf_decomposition_test
00:42 FAIL landice_greenland_fo_decomposition_test
00:42 FAIL landice_greenland_fo_restart_test
00:37 FAIL landice_thwaites_decomposition_test
00:44 FAIL landice_thwaites_restart_test
00:51 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 07:50
```
All failures are baseline comparison failures (i.e. test validation passes).  I will look into the failures next and make sure they are what we expect.  I'm a little surprised to see the GIS SIA test failing but the humboldt test passing.  But it's conceivable the mask changes are such that this would occur.

2022-10-19 22:30 UTC, matthewhoffman commented
`landice_greenland_sia_restart_test`: differences Linf: thickness=10^-10, normalVelocity=10^-13
`landice_greenland_sia_decomposition_test`: differences Linf: thickness=10^-10, normalVelocity=10^-13
`landice_greenland_fo_decomposition_test`: differences Linf: thickness=10^-3, normalVelocity=10^-7
`landice_greenland_fo_restart_test`: differences Linf: thickness=10^-3, normalVelocity=10^-7
`landice_thwaites_decomposition_test`: differences Linf: thickness=10^-1, surfaceSpeed=10^-5
`landice_thwaites_restart_test`: differences Linf: thickness=10^0, surfaceSpeed=10^-5

For Thwaites test, thickness difference is only significant precisely where the floating dynamic mask changes:
![image](https://user-images.githubusercontent.com/4182034/196816580-4f86ed89-1fc3-49fa-8956-980cc2aa2e9f.png)

Looking through these differences, I am comfortable with the differences and prepared to declare this successful.  I'm still surprised the humboldt test is showing no difference at all from the baseline, but it's conceivable given the short duration of these tests and the fact that the initialization of the floating dynamic mask has not really changed.

I will redo my ISMIP6 active calving runs to make sure this modified PR still solves the original problem it set out to and the results otherwise look ok and similar to before.

2022-10-20 15:33 UTC, trhille commented
Results from the humboldt_calving_tests_fo suite against a baseline on develop commit a64342f:
```
01:19 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-none
01:02 PASS landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-floating
01:15 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-eigencalving
01:10 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-specified_calving_velocity
01:15 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-von_mises_stress
01:13 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-damagecalving
00:11 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-ismip6_retreat
01:11 FAIL landice_humboldt_mesh-3km_decomposition_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
00:57 FAIL landice_humboldt_mesh-3km_restart_test_velo-fo_calving-none
00:49 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-floating
00:52 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-eigencalving
00:50 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-specified_calving_velocity
00:53 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress
00:50 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-damagecalving
00:08 FAIL landice_humboldt_mesh-3km_restart_test_velo-fo_calving-ismip6_retreat
00:51 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
```
Of these, baseline comparison failures are:
```
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-none
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-eigencalving
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-specified_calving_velocity
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-von_mises_stress
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-damagecalving
landice/humboldt/mesh-3km_restart_test/velo-fo_calving-none
```
Validation failure, which passes baseline comparison:
```
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
```
Execution errors, which also occur in the baseline suite:
```
landice/humboldt/mesh-3km_decomposition_test/velo-fo_calving-ismip6_retreat
landice/humboldt/mesh-3km_restart_test/velo-fo_calving-ismip6_retreat
```

2022-10-20 15:43 UTC, matthewhoffman commented
Assessment of impact of redefining dynamic floating mask on ISMIP6 runs.  These results are with **fixed calving front**.

solid=without the mask changes (using [566a8c6](https://github.com/MALI-Dev/E3SM/pull/50/commits/566a8c67f6a9688b3b0d3878472c0e20c69956df))
dotted=initial implementation of mask changes (that were still buggy and probably garbage) (using [a9df714](https://github.com/MALI-Dev/E3SM/pull/50/commits/a9df7144254892996d27346f36b69c8adaef1ea3))
dashed=final version of mask changes (plus #37) (using [e457d37](https://github.com/MALI-Dev/E3SM/pull/50/commits/e457d3776090510b5a742908e6b74bfa4c003683))

Overall the differences between all three versions are small, which is good.  The differences are only significant in basins with small ice shelves and/or significant grounded marine termini (e.g. Totten, Mertz, Thwaites), as one would expect based on the nature of the changes.  The incomplete/buggy version generally led to greater mass loss than the original version.  The completed version is much closer to the original mass trend, which I think is a good thing.

However, I'm a bit confused, because the whole reason I made these changes was to deal with areas at ice shelf/grounded termini junctions experiencing sudden, unrealistic speedups when the mask definition changes after small changes in ice thickness.  That typically was leading to faster retreat (after such a speedup occurred), but these plots are showing the mask change leads to faster retreat, not slower (where it makes a difference at all).  However, that was all for the case of evolving calving fronts, so I should redo this comparison for that situation, plus look at the maps of velocity to ensure those sudden changes are in fact reduced.

![image](https://user-images.githubusercontent.com/4182034/196992961-8146ac3e-497d-43dd-b92d-54ac91a65996.png)

2022-10-20 17:31 UTC, matthewhoffman commented
Same plot but including runs **with evolving calving**.

solid=no calving, before mask change (same as previous plot)
dotted=no calving, final mask change (same as previous plot)
dashed=with calving, before mask change
dashdot=with calving, final mask change

As seen in the last plot, for no calving cases, this mask changes leads to faster mass loss for regions with small ice shelves and/or extensive grounded margins.  For the calving cases, there appears to be very little impact of the mask change.  Mass loss with calving is notably faster for basins with small ice shelves relative to no-calving, but that's not related to this PR.

So it seems fair to conclude this mask change does no harm, but it also doesn't seem to impact the original issue it was intended to resolve, which was too-fast mass loss due to spurious speedup of small ice shelves when the mask changes.  I will next look at maps of speed to see if in fact that spurious speedup is reduced (even if it isn't changing mass loss much).  If so, we might still want to keep these changes for that reason alone.  But if it is not actually reducing that problem, then we probably don't want to actually make these mask changes, because of the extra complexity that they add.

![image](https://user-images.githubusercontent.com/4182034/197005653-5a32adb7-a936-4ebd-a4cc-25dcc34317fb.png)

2022-10-20 20:46 UTC, closed without merging