Calving mask and restore calving improvements
MALI-Dev/E3SM pull request #53
Opened 2022-11-18 16:26 UTC by matthewhoffman

This PR introduces a number of usability changes to the mask-calving and restore_calving_front functionalities.  These changes are necessary to run the ISMIP6 Tier2 experiments that include a mask for where ice should be calved.  The changes are:
* allowing restore_calving_front to be applied after a calving law is applied.  Previously, restore_calving_front and actual calving laws were mutually exclusive.
* creating an option for restore_calving_front to allow retreat.  Previously, restore_calving_front would replace a thin layer of ice out to the original calving front if the calving front retreated for any reason (e.g. melted through).  Preserving the original ice-shelf extent is needed for coupled E3SM runs where the coupler can not yet support a change in ice-shelf extent.  But for standalone runs, we often want to disallow calving front advance but retreat is ok (and preferable to an artificial thin layer of ice).  The default behavior of the new option retains backwards compatible behavior.
* allowing mask calving to be applied in addition to a physically based calving law.  This allows the configuration where we have von Mises (or other) calving law active, but still want to apply the ice-shelf collapse mask from ISMIP6.  
* adding a new field called calvingThicknessFromThreshold that tracks the thickness of ice in each cell removed by any threshold calving process (a subset of what previously has been recorded only in calvingThickness).  This facilitates post-processing of calving flux for ISMIP6 by allowing different calculations for rate-based calving (e.g. von Mises) and threshold-based calving laws.  Implementation of this new field required reorganizing how certain fields are initialized.

2022-11-18 16:31 UTC, matthewhoffman commented
Results for mask calving showing correct application of calving mask.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/4182034/202753896-09238505-ccb5-4a64-a16a-b3844f59cc88.png">

Note that because forcing is currently read at the end of a time step, the mask gets applied on the following time step.  I think this is something we should re-evaluate but it beyond the scope of this PR, and we should not attempt to change that in the middle of the ISMIP6 runs.

2022-11-18 16:45 UTC, matthewhoffman commented
Snapshot showing the when restore_calving_front is on, surfaceSpeed gets inserted as the calvingVelocity in places where restore_calving_front prevented advance.  In places where the calving front has retreated from the initial calving front (here, due to mask calving, in green), restore_calving_front does not assign a calvingVelocity, because it is not operating there.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/4182034/202756927-3cfc0fa3-2b80-4b37-ad93-133e78c40de8.png">

2022-11-18 19:09 UTC, matthewhoffman commented
COMPASS fails the following baseline comparisons:
```
landice_greenland_sia_restart_test
landice_greenland_sia_decomposition_test
landice_greenland_fo_decomposition_test
landice_greenland_fo_restart_test
landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
```

I suspect this is from differences related to order of operations with restore-calving-front and probably can be blessed, but we should confirm that before proceeding.  I don't have time to look into it right now but will look later.

2022-11-18 20:03 UTC, trhille requested changes
@matthewhoffman, these changes make sense to me. I added a few minor requests for changes that shouldn't affect functionality.

2022-11-18 21:10 UTC, matthewhoffman commented
The greenland sia tests have diffs of 10^-4 m in thickness and 10^-26 m/s in normalVelocity from the baseline.
The greenland fo tests have diffs of 10^-3 m in thickness from the baseline and no diff in normalVelocity from the baseline.
The humboldt test has no diff from baseline in thickness, surfaceSpeed, or faceMeltingThickness. and diffs of 10^-22 m/s in calvingVelocity, 10^-16 in calvingThickness, and 10^-16 in damage.

I'm inclined to say these diffs are acceptably small and not worth tracking down.  But we can also try to understand exactly where they come in if desired.

2022-11-18 23:49 UTC, trhille commented
My compass testing on testing on a test merge of this branch into `MALI-Dev/develop` confirms @matthewhoffman 's numbers above. These differences are not worth figuring out.

I also ran the `humboldt_calving_tests` suite and all tests passed baseline comparison (although both `velo-none_calving-ismip6_retreat` tests failed execution in both baseline and comparison runs)

`humboldt_calving_tests_fo` suites are still running here: `/global/cscratch1/sd/trhille/test_MALI-Dev_PR53/baseline/humboldt_calving_tests_fo` and `/global/cscratch1/sd/trhille/test_MALI-Dev_PR53/comparison/humboldt_calving_tests_fo`

2022-11-21 15:41 UTC, matthewhoffman commented
@trhille , thanks for looking this over.  I pushed a new commit with the requested changes.  The one log message that you requested adding indexToCellID I instead commented out.  I had been using that line for debugging and had not intended it to be active in debugging runs.

2022-11-21 18:08 UTC, trhille approved these changes
Thanks for taking care of these small changes!

2022-11-21 18:23 UTC, trhille commented
`humboldt_calving_tests_fo` suite passes all baseline comparisons. However, many tests fail validation and the `ismip6_retreat` tests fail execution in both baseline and comparison suites, so we should look into that soon.

2022-11-21 18:45 UTC, merged