Use 3D thermal forcing for to calculate grounded face-melting
MALI-Dev/E3SM pull request #58
Opened 2022-12-21 02:02 UTC by trhille

This merge adds to ability to use a 3D ocean thermal forcing field in the ISMIP6/Rignot (2016) face-melting parameterization for grounded marine margins. If the new namelist option `config_use_3d_thermal_forcing_for_face_melt`, the relevant 2D thermal forcing is calculated from `ismip6shelfMelt_3dThermalForcing` and `bedTopography`. As in Slater et al. (2020), it uses the thermal forcing at the ocean floor. Another approach would be to use a depth-averaged thermal forcing, but the treatment used here is consistent with ISMIP6.
This also sets default values for `ismip6shelfMelt_3dThermalForcing` and `ismip6_2dThermalForcing` to 0.0 instead of 2.0. The previous implementation was dangerous because it could create a reasonable melt field even if the input streams were incorrect and thermal forcing data was not being read.

2022-12-21 02:11 UTC, trhille commented
Testing on the 4–20km AIS mesh used for ISMIP6 shows nothing unexpected. Here is the 2D thermal forcing field calculated from the 3D field using the ISMIP6 observational climatology forcing:
![image](https://user-images.githubusercontent.com/17446278/208803230-a2956ef5-2db6-4838-a6c9-7fb3d08271f7.png)
Here is `faceMeltingThickness` in the Bellinghausen sector after 31 years of integration, showing that melt rates are generally low (up to a few meters in a 47-day timestep):
![image](https://user-images.githubusercontent.com/17446278/208803925-b6a1f467-de59-4cdc-acbf-2c5c59abdd77.png)

2022-12-22 20:46 UTC, matthewhoffman requested changes
@trhille , this is a very useful addition, and thanks for getting it implemented so quickly.

I have a few small adjustments that I think would be worth making.

2022-12-22 20:46 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                            description="If true, use ismip6shelfMelt_3dThermalForcing and associated variables to calculate a depth-averaged thermal forcing for use with the config_front_mass_bal_gr
bottom depth TF, not depth-averaged, right?

2022-12-22 20:46 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe.F
> +      elseif (CFLprocess == 4) then
Also, please update the description of `CFLprocess` in Registry

2022-12-22 20:46 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="ismip6shelfMelt_3dThermalForcing" packages="ismip6ShelfMelt;ismip6GroundedFaceMelt"/>
Instead of adding the `ismip6GroundedFaceMelt` package to all these variables (so that we have these 3d fields allocated even if using 2d forcing), what do you think about instead modifying the definition of the `ismip6ShelfMelt` package to include the situation where facemelting is on and set to use 3d TF?  That would be line 158 of `mpas_li_core_interface.F`

2022-12-22 21:32 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe.F
> +      elseif (CFLprocess == 4) then
resolved in ebce6d70db1394470386b77fda411d7507c9342b

2022-12-22 21:32 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +                            description="If true, use ismip6shelfMelt_3dThermalForcing and associated variables to calculate a depth-averaged thermal forcing for use with the config_front_mass_bal_gr
resolved in ebce6d70db1394470386b77fda411d7507c9342b

2022-12-22 21:32 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +                        <var name="ismip6shelfMelt_3dThermalForcing" packages="ismip6ShelfMelt;ismip6GroundedFaceMelt"/>
resolved in ebce6d70db1394470386b77fda411d7507c9342b

2022-12-22 21:32 UTC, trhille commented
Passes all compass baseline comparisons.

2023-01-04 17:23 UTC, trhille commented
Testing the new implementation shows that the correct layer from `ismip6shelfMelt_3dThermalForcing` is being sampled to create `ismip6_2dThermalForcing`. I tested this on the Thwaites_1to8km_r02 mesh, using ismip6 climatology forcing writing out `ismip6shelfMelt_3dThermalForcing` and `ismip6_2dThermalForcing` every time step (all time-steps should be identical for the climatology forcing). I then used the following python code to ensure that `ismip6_2dThermalForcing` is correct everywhere for the first 20 time steps:
```
count = 0;
bad_iCell = []
bad_iCell_3d = []
bad_iCell_2d = []
for iTime in np.arange(0, 20):
    print(f"time={iTime}")
    for iCell in np.arange(0, nCells):
        if bed[iTime,iCell] < 0.0:
            z_index = np.argmin(np.abs(zOcean - bed[iTime,iCell]))
            if ((zOcean[z_index] - bed[iTime,iCell]) < 0.):
                z_index -= 1
            z_index = max(z_index, 0)
            if TF_2d[iTime,iCell] != TF_3d[iTime,iCell,z_index]:
                count += 1
                bad_iCell.append(iCell)
                bad_iCell_2d.append(TF_2d[iTime,iCell])
                bad_iCell_3d.append(TF_3d[iTime,iCell,z_index])
```
`count` is 0 at the end of this loop over all cells in the first 20 time steps, indicating that `ismip6_2dThermalForcing` is correct.

2023-01-04 17:26 UTC, trhille commented
All compass tests pass baseline comparison.

2023-01-04 21:08 UTC, trhille commented
After implementing interpolation in [1db071e](https://github.com/MALI-Dev/E3SM/pull/58/commits/1db071eede3649674998dca9ece88580c162dc9d), testing shows that this is behaving as expected. I randomly sampled five cells from each of the first four timesteps of a test run on the Thwaites_1to8km_r02 mesh using ismip6 climatology forcing. Here are depth profiles of `ismip6shelfMelt_3dThermalForcing` (blue), with the bed depth (black), and interpolated `ismip6_2dThermalForcing` (orange). Subplots within each column are identical, indicating no change over time, as expected.
![image](https://user-images.githubusercontent.com/17446278/210650118-6a05a842-524e-4770-a3bd-f47a950162d2.png)

2023-01-04 21:10 UTC, trhille commented
Here is the interpolated 2D thermal forcing field:
![image](https://user-images.githubusercontent.com/17446278/210650436-2043082c-9e3e-49d8-a9e1-65e5abdef1c6.png)
And a zoom in on the modern terminus region:
![image](https://user-images.githubusercontent.com/17446278/210650518-f616fbdb-6633-4889-922f-960b1dd2a221.png)

2023-01-04 21:18 UTC, trhille commented
All compass tests using [1db071e](https://github.com/MALI-Dev/E3SM/pull/58/commits/1db071eede3649674998dca9ece88580c162dc9d) pass baseline comparison.

2023-01-05 04:04 UTC, matthewhoffman approved these changes
@trhille , thanks for the continued refining of this feature and the thorough testing.  Those depth profiles are very convincing.  I also ran COMPASS regression test and get the same result of all baseline comparisons passing.

2023-01-05 04:08 UTC, merged