Hollyhan/mali/add ocean thermal forcing re extrapolation
MALI-Dev/E3SM pull request #64
Opened 2023-01-23 22:10 UTC by hollyhan

Note: this PR is currently in progress (as of January 2023)

This PR adds the new module to MALI that extrapolates ocean data (temperature, salinity, thermal forcing, etc.) from the ocean model/observation domain into the MALI domain. The ocean model domain does not extend underneath the ice shelves in MALI, and ocean observation data is spatially sparse, requiring one to extrapolate the data onto the MALI domain. The concept of the scheme is very similar to that in Jourdain et al. 2020, but the algorithm and implementation still differ; for example, MALI will not calculate sparse matrix per basin as in Jourdain et al.(2020), but instead use what is very similar to the `li_flood_fill` routine in the ‘mpas_li_calving.F’ module.

2023-03-04 08:37 UTC, xylar commented on components/mpas-albany-landice/src/Registry.xml
> +		</nml_record>
@hollyhan, it's an odd quirk of the registry that the indentation here is with tabs rather than spaces.  This is pretty easy to see on GitHub because things don't line up quite right.  Please make sure all indentation is with tabs.

2023-03-04 08:39 UTC, xylar commented
@hollyhan, I'm assuming this PR is mostly a place for discussion for now. Let us know if you want us to start reviewing or if there are particular areas where you have questions.

2023-03-04 08:39 UTC, xylar commented
Before we get too far, it would be good to have the PR title replaced with something meaninful.

2024-01-11 18:45 UTC, matthewhoffman requested changes
@hollyhan , thanks for the work on this PR!  I think it will be a useful tool for a lot of applications.  I looked it over today with @alexolinhager and I made a number of small comments.  I will review again when you consider it done, but I figured it might be helpful for me to share those comments now.

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         ! create a 2D mask based on the open ocean + floating ice +  grounded ice mask and n-extra cells into the grounded ice
```suggestion
         ! create a 2D mask based on the open ocean + floating ice +  grounded ice mask to be used for defining the location of the n-extra cells into the grounded ice
```

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         ! Start horizontal floodfill
```suggestion
         ! Start horizontal floodfill to define locations of n-extra cells
```

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +            ! Update halos
Add a comment that halo updates could be skipped for a number of iterations equal to the number of halo rows as a possible performance improvement in the future.  (And the loop above would need to be changed to from `nCellsSolve` to `nCells`)

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         call mpas_timer_stop("halo updates")
For this chunk of code, it will be more efficient and equally correct to remove the halo update and loop over `nCells`.

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         call mpas_log_write('ocean data will NOT be extrapolated into the MALI ice draft')
Once this is no longer needed for debugging purposes, please delete this log message - it's not necessary to report that this won't be called.

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +         do while (newMaskCountGlobal > 0)
Maybe we want a log statement indicating the iteration through this loop in case things ever get stuck.  On that note, let's add an max iter check of something like 10 or 20 iterations to kill the model if the code ever gets stuck in this loop.

2024-01-11 18:45 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +                 TFocean(iLayer,iCell) = (TFocean(iLayer-1,iCell)) + (60 * 0.0008) !HH: need to correct for pressure melting point change
flagging this note for updating

2024-08-26 18:13 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +                    TFocean(iLayer,iCell) = (TFocean(iLayer-1,iCell)) + (60 * 0.0008)
What are these constants?

2024-08-26 18:44 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                     description="gamma0 value prescribed for ISMIP6 ice-shelf melting method, ismip6shelfMelt_zBndsOcean to model.  Defaults to 0 so that missing input value will zero melt field."
```suggestion
                     description="gamma0 value prescribed for ISMIP6 ice-shelf melting method, input to model.  Defaults to 0 so that missing input value will zero melt field."
```

2024-08-26 19:28 UTC, xylar commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +                    TFocean(iLayer,iCell) = (TFocean(iLayer-1,iCell)) + (60 * 0.0008)
I think the first should be the ISMIP6 layer thickness `z(iLayer-1) - z(iLayer)`.  The second is a linearization of the change in freezing temperature as a function of depth.  Hopefully, @hollyhan has notes on this.  It should not be hard coded, it should be a namelist parameter and there should be documentation on how it was derived.

2024-08-26 21:53 UTC, matthewhoffman commented
# Testing

Results of `full_integration` suite on Perlmutter.  Note that new feature is not being tested, but this confirms it does not break any existing behavior (after most recent commit).

```
Test Runtimes:
00:32 PASS landice_dome_2000m_sia_restart_test
00:13 PASS landice_dome_2000m_sia_decomposition_test
00:13 PASS landice_dome_variable_resolution_sia_restart_test
00:08 PASS landice_dome_variable_resolution_sia_decomposition_test
00:33 PASS landice_enthalpy_benchmark_A
00:26 PASS landice_eismint2_decomposition_test
00:29 PASS landice_eismint2_enthalpy_decomposition_test
00:26 PASS landice_eismint2_restart_test
00:28 PASS landice_eismint2_enthalpy_restart_test
00:16 PASS landice_greenland_sia_restart_test
00:10 PASS landice_greenland_sia_decomposition_test
00:27 PASS landice_hydro_radial_restart_test
00:21 PASS landice_hydro_radial_decomposition_test
00:35 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-none_subglacialhydro
00:35 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-none_subglacialhydro
00:27 PASS landice_dome_2000m_fo_decomposition_test
00:26 PASS landice_dome_2000m_fo_restart_test
00:17 PASS landice_dome_variable_resolution_fo_decomposition_test
00:17 PASS landice_dome_variable_resolution_fo_restart_test
00:18 PASS landice_circular_shelf_decomposition_test
00:48 PASS landice_greenland_fo_decomposition_test
00:43 PASS landice_greenland_fo_restart_test
00:26 PASS landice_thwaites_fo_decomposition_test
00:36 PASS landice_thwaites_fo_restart_test
00:16 PASS landice_thwaites_fo-depthInt_decomposition_test
00:22 PASS landice_thwaites_fo-depthInt_restart_test
00:39 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
00:19 PASS landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 12:26
PASS: All passed successfully!
```

2024-08-26 22:02 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +                    TFocean(iLayer,iCell) = (TFocean(iLayer-1,iCell)) + (60 * 0.0008)
Thanks, @xylar .  After I asked this, I did find a Slack exchange I had Holly some time ago about this, which is where my subsequent modification that you saw came from.  Are you ok with they way I implemented it, using the value we had in `li_constants` rather than a namelist option?  I did commit your flip to the depth differencing and operator sign.

2024-08-27 06:52 UTC, xylar commented on components/mpas-albany-landice/src/mode_forward/mpas_li_ocean_extrap.F
> +                    TFocean(iLayer,iCell) = (TFocean(iLayer-1,iCell)) + (60 * 0.0008)
Yes, I'm fine with your current constant rather than a namelist operation. Thanks!

2024-08-27 15:57 UTC, matthewhoffman commented
# Evaluation
Example result using `ismip6_run/ismip6_ais_proj2300` 4km configuration for `hist` experiment.  This uses the `AIS_4to20km_r01_20220907_obs_TF_1995-2017_8km_x_60m.nc` TF forcing file.

Extrapolation settings:
```
    config_ocean_data_extrapolation = .true.
    config_ocean_data_extrap_ncells_extra = 5
    config_invalid_value_TF = 1.0e36
    config_weight_value_cell = 0.7
```

Image is extrapolated TF for z-level 7 (depth=-390 m)

Results look as expected, and we can see that over-extrapolation.  Subsequent time levels show the expected adjustment in extrapolation extent based on grounding line migration.
![image](https://github.com/user-attachments/assets/5d07003f-cbaf-4455-84ad-6f165581718e)

2024-08-27 17:57 UTC, xylar commented
Maybe give the PR a proper name...

2024-08-27 18:21 UTC, merged

2024-08-27 18:27 UTC, xylar commented
Ha, ha!  I see you beat me to it.  Missed that.

2024-08-27 18:49 UTC, matthewhoffman commented
After months of stagnation, things are moving fast on this PR! :)