Add flux-corrected transport scheme to MALI
MALI-Dev/E3SM pull request #70
Opened 2023-03-07 20:35 UTC by trhille

This merge adds a flux-correct transport scheme to MALI for tracer advection, which should be a significant improvement over the first-order upwinding currently used.

2023-03-09 22:52 UTC, trhille commented
Code compiles as of [commit 414eac603fb](https://github.com/MALI-Dev/E3SM/pull/70/commits/414eac603fb8d1b0921a6659521f8f0d4a6c6c52)

2023-03-10 17:54 UTC, trhille commented
`full_integration` passes as of [83f5168](https://github.com/MALI-Dev/E3SM/pull/70/commits/83f51685ca7b6cd542770093baf9c30162361e0b), which does not test the fct at all, but indicates that the new `li_mesh` and `li_config` modules are operational.

2023-03-14 22:41 UTC, trhille commented
Testing on https://github.com/MALI-Dev/E3SM/pull/70/commits/a364f7a04a1a71284257e3c51f5abdcde66ba1a0 shows that the code will run with `config_thickness_advection = 'fo'` and `config_tracer_advection = 'fct'`, but tracers don't seem to actually be advecting.

2023-03-16 15:02 UTC, trhille commented
As of https://github.com/MALI-Dev/E3SM/pull/70/commits/e85d3fdf943a1f61e7fdd06e89a0bc43566d057a, fct tracer advection is at least doing something, although is not yet verified. Here are three MISMIP runs with velo solver turned off, no sub-shelf melt, calculate-damage = true. All use 'fo' thickness advection. Left: no tracer advection; Middle: fo tracer advection; right: fct tracer advection:
![image](https://user-images.githubusercontent.com/17446278/225658732-3d36eb3b-5f5d-4104-8c8c-179b4584d59e.png)

2023-03-16 21:47 UTC, trhille commented
As of https://github.com/MALI-Dev/E3SM/pull/70/commits/87343038ed4c7e3efc95635d64e28d925b8e5c8f, fct thickness advection is operational, and seems to be working correctly. One issue is that it seems to require a very small CFL fraction to avoid terracing effects.
From left to right: fo thickness advection with CFL fraction = 0.8; fct thickness advection w/ CFL fraction 0.8; fct thickness advection w/ CFL fraction 0.1:
![image](https://user-images.githubusercontent.com/17446278/225759367-0e96b5c4-7f62-4c66-b1d5-276f181219a0.png)

CFL fraction of 0.1  (~40 day time steps) seems to be sufficiently low here. I tested another run w/ a CFL fraction of 0.01 (~4 days) and the differences at year 100 are generally <1 m:
![image](https://user-images.githubusercontent.com/17446278/225759706-95179f02-2124-4f3d-90eb-67a2d51d9944.png)


What we are seeings seems to be a  known issue w/ FCT: "Another infamous byproduct of FCT manifests itself in distortions of a smooth profile. This phenomenon is known as terracing and represents ‘an integrated, nonlinear effect of residual phase errors’ [64] or, loosely speaking, ‘the ghosts of departed ripples’ [7]. A particularly severe form of terracing is caused by the linear instability of the high-order scheme. For this reason, we do not recommend the use of the forward Euler time-stepping (θ = 0) even though the flux-corrected scheme proves positivity-preserving under the CFL-like time step restriction (62)."
(found on page 178 of https://link.springer.com/content/pdf/10.1007/978-94-007-4038-9.pdf)

2023-03-16 22:03 UTC, trhille commented
Adding to comment above: CFL fraction of 0.4 also drastically reduces the terracing and gives a thickness field visually indistinguishable from CFL fractions of 0.1 and 0.01, so that's great news!

2023-03-17 17:26 UTC, trhille commented
Testing on Thwaites mesh indicates issue with FCT thickness advection during advance, which is not surprising. It turns out that `boundaryCell` is not being calculated, and thus neither is `advMaskHighOrder`. This leads to very high velocities and strange geometries in areas where ice advances beyond the initial extent.

2023-03-27 22:45 UTC, trhille commented
As of https://github.com/MALI-Dev/E3SM/pull/70/commits/4c87809fe6822b2d6903ab77f6a4b0971ac85f4b, fct thickness advection is actually working! I tested this on an altered MISMIP domain, in which I set bedTopography = 0.0 everywhere, thickness = 1000 on the left side of the domain, and imposed a 1km/yr left-to-right velocity field. I added a notch in thickness of 500 m, and a passive tracer at that location as well.
The initial condition looks like this:
![image](https://user-images.githubusercontent.com/17446278/228081408-342c0358-20c6-4578-9bfe-4c0849690d50.png)

Here is the 3rd order solution (3rd order coeff = 0.25) after 25 years:
![image](https://user-images.githubusercontent.com/17446278/228082473-69f24468-7690-4950-a663-8ff1ce23ef6f.png)

Here are the solutions of thickness and passiveTracer along a transect down the center of the domain from left to right:
![image](https://user-images.githubusercontent.com/17446278/228083183-bb48942f-001d-425c-ad8a-d203ed8694e4.png)
![image](https://user-images.githubusercontent.com/17446278/228083550-07a5790c-c7a2-451f-b9ba-f21b99a2a8ca.png)

2023-04-21 17:01 UTC, trhille commented
As of [5889ba6](https://github.com/MALI-Dev/E3SM/pull/70/commits/5889ba68b25a2947bff1a0cf2d3f73c7967575d8), fct thickness advection actually conserves mass!
Here are two 3rd order (beta = 0.5) slotted cylinder runs w/ no surface or basal mass balance. Blue curve uses 5889ba6, orange uses 4f313f1:
![image](https://user-images.githubusercontent.com/17446278/233693077-9e3a4afd-5c77-41b9-a644-18f30471b199.png)
Here is volume change for just the 5889ba6 run:
![image](https://user-images.githubusercontent.com/17446278/233693187-c2823083-250e-49c5-871b-08c4d6a064b3.png)
It also makes the results look visibly better. Here is the slotted cylinder at year 25; the left column is 5889ba6, right is 4f313f1:
![image](https://user-images.githubusercontent.com/17446278/233693461-a2c9b528-34c3-40e0-a077-6b50cf6811c4.png)

I'm not sure why one edge of the cylinder is eroding in the left-hand column, but mass is conserved and the cylinder isn't splatting outwards like it is in the right-hand column, so I'm pretty happy with it!
![image](https://user-images.githubusercontent.com/17446278/233693680-2ffdf046-9a19-41cc-8a48-24430bc1159e.png)

2023-04-24 15:48 UTC, trhille commented
I have confirmed that results are BFB for restarts and decomposition tests (64 and 128 cores) using the slotted cylinder test case.

2023-04-24 16:03 UTC, trhille commented
Here are results at year 25 with CFL fractions of 0.25 (top), 0.1 (middle) and 0.05 (bottom):
![image](https://user-images.githubusercontent.com/17446278/234052921-3eed1a72-86f5-4c8d-9144-7235925da943.png)

2023-08-01 19:27 UTC, trhille commented
Uh oh, it appears that `passiveTracer` is not being conserved in test runs with either fct or fo advection. I ran the notched slab test that I was using above for 100 years and summed up `passiveTracer` at each time step (uniform cell spacing, so no need to account for `areaCell`).
fct:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/be0aafa1-123d-4500-9017-e526d8225fe0)
fo:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/96bb282e-eb87-469a-8b6e-33986017c1b9)

2023-08-03 18:51 UTC, trhille commented
[8d2f023](https://github.com/MALI-Dev/E3SM/pull/70/commits/8d2f02312b2edb4169751858ce2cdbaf988a2b9d) fixed the tracer conservation issue detailed above! It still doesn't conserve to machine precision, but a 100 year test run on the grounded slab test case showed about 0.06% drift by the end of the simulation. That seems pretty close!

Compare this with the drift above
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/95262c8f-e318-4bc6-9281-3518127d7d01)

2023-08-16 16:16 UTC, matthewhoffman commented
@dengwirda, see note about slight non-conservation of tracers in Trevor's current implementation (https://github.com/MALI-Dev/E3SM/pull/70#issuecomment-1664471184).  Should we be expecting machine precision conservation?  If so, do you think we should worry that we're not achieving that given how small the non-conservation is?

I suppose we would be introducing energy conservation errors, given that we will be advecting temperature with this scheme.

2023-08-16 16:48 UTC, matthewhoffman requested changes
@trhille , I've made it through these changes and have a number of requests and questions to address, but this seems very close to being ready to merge.  Thanks for you hard work and what turned out to be a much more involved project than initially anticipated!

2023-08-16 16:48 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection_fct_shared.F
> +      advMaskHighOrder, & ! mask for high order advection terms
@trhille , please clarify the description of these masks.  They are meant to represent where the HO terms are valid (as opposed to invalid), right?  `adv` abbreviates "advection" and not "advance", right?

2023-08-16 16:48 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection_fct.F
> +                                    (advMaskHighOrder(k,iEdge) + advMask2ndOrder(k,iEdge) &
Can you add a code comment explaining this masking?  e.g. 
`! only remove low order flux where high order flux is valid to avoid introducing nonzero values to highOrderFlx where it is invalid`

(the title of the commit that introduces this was confusing to me, but don't bother to change the history - updating the explanation in-code is a more durable clarification.)

2023-08-16 16:48 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                  nTracers, activeTracerHorizontalAdvectionEdgeFlux, computeBudgets=.false.)!{{{
We may want to move `activeTracerHorizontalAdvectionEdgeFlux` to Registry so it could be output given its importance in the algorithm.  But we'd want to refactor things to avoid it being `nTracers` big first.  So let's wait until we encounter a need to visualize it before worrying about that.

2023-08-18 16:37 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection_fct_shared.F
> +      advMaskHighOrder, & ! mask for high order advection terms
Correct, `adv` is for "advection". I'd prefer not to change it to make it longer, since the comments clarify it and this is consistent with the variable names in MPAS-O.

2023-08-18 21:21 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +             ! TODO: determine whether we need to treat other tracer tendencies
Yes, it doesn't work for tracers, for some reason.

2023-08-18 21:22 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                  nTracers, activeTracerHorizontalAdvectionEdgeFlux, computeBudgets=.false.)
Made optional in 9530ad59f

2023-08-19 06:08 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +                <var name="passiveTracer" type="real" dimensions="nCells Time" units="none" time_levs="1"
Why doesn't this need to include a dimension of nVertLevels?

2023-08-28 18:13 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                  tend, advectedTracers, layerThicknessOld * 0.0_RKIND + 1.0_RKIND, &
Addressed in f43c26bcf8037286667b74a721744beb2799e1e2

2023-08-28 18:23 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +                <var name="passiveTracer" type="real" dimensions="nCells Time" units="none" time_levs="1"
addressed in 8f218c3167c3761d50350a9b2e6cc3547740c5dc

2023-08-31 17:32 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection_fct_shared.F
> +      advMaskHighOrder, & ! mask for high order advection terms
Ok, that makes sense.

2023-08-31 17:32 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection_fct.F
> +#ifdef MPAS_OPENACC
We decided to save removing accelerator stuff for a separate PR.

2023-08-31 17:44 UTC, matthewhoffman requested changes
@trhille , thanks for all the clean up on this PR.  I would like to proceed with merging the version you have now and resolve additional issues related to conservations and convergence in follow up PRs as we learn more.  

However, it would be nice to first add the logic to support FCT thickness advection with no tracer advection.  That would be useful for the horizontal_advection convergence test using the thickness bump and for the halfar convergence test.  I think disabling tracer advection would speed those tests up considerably.

One solution would be to fold it into this option:
```
         elseif ((trim(config_thickness_advection) .eq. 'fct') .and. &
                  trim(config_tracer_advection) .eq. 'fct') then
```
and then only do the tracer bit if tracer advection is set to fct.

2023-09-06 03:01 UTC, matthewhoffman commented
@trhille , thanks for making the final (more complicated than expected) adjustment.  I tested one more time and all tests pass:
```
Test Runtimes:
00:19 PASS landice_dome_2000m_sia_restart_test
00:19 PASS landice_dome_2000m_sia_decomposition_test
00:16 PASS landice_dome_variable_resolution_sia_restart_test
00:06 PASS landice_dome_variable_resolution_sia_decomposition_test
00:26 PASS landice_enthalpy_benchmark_A
00:24 PASS landice_eismint2_decomposition_test
00:23 PASS landice_eismint2_enthalpy_decomposition_test
00:29 PASS landice_eismint2_restart_test
00:28 PASS landice_eismint2_enthalpy_restart_test
00:22 PASS landice_greenland_sia_restart_test
00:12 PASS landice_greenland_sia_decomposition_test
00:20 PASS landice_hydro_radial_restart_test
00:12 PASS landice_hydro_radial_decomposition_test
00:44 PASS landice_humboldt_mesh-3km_decomposition_test_velo-none_calving-none_subglacialhydro
00:30 PASS landice_humboldt_mesh-3km_restart_test_velo-none_calving-none_subglacialhydro
00:26 PASS landice_dome_2000m_fo_decomposition_test
00:30 PASS landice_dome_2000m_fo_restart_test
00:11 PASS landice_dome_variable_resolution_fo_decomposition_test
00:16 PASS landice_dome_variable_resolution_fo_restart_test
00:18 PASS landice_circular_shelf_decomposition_test
00:44 PASS landice_greenland_fo_decomposition_test
00:44 PASS landice_greenland_fo_restart_test
00:41 PASS landice_thwaites_fo_decomposition_test
00:32 PASS landice_thwaites_fo_restart_test
00:15 PASS landice_thwaites_fo-depthInt_decomposition_test
00:22 PASS landice_thwaites_fo-depthInt_restart_test
00:58 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
00:32 PASS landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 12:04
PASS: All passed successfully!
```
I will also test the FCT tests you have in https://github.com/MPAS-Dev/compass/pull/650

2023-09-06 03:15 UTC, matthewhoffman commented
# Testing, Part 2

The FCT suite all passes.  I did not look at any of the output, but they all run and pass validation.  For the sake of merging this PR as a checkpoint, I think that is sufficient.

```
Test Runtimes:
00:19 PASS landice_dome_2000m_fo_fct_decomposition_test
00:35 PASS landice_dome_2000m_fo_fct_restart_test
00:16 PASS landice_dome_variable_resolution_fo_fct_decomposition_test
00:14 PASS landice_dome_variable_resolution_fo_fct_restart_test
00:42 PASS landice_greenland_fo_fct_decomposition_test
00:47 PASS landice_greenland_fo_fct_restart_test
00:38 PASS landice_thwaites_fct_decomposition_test
00:34 PASS landice_thwaites_fct_restart_test
00:35 PASS landice_humboldt_mesh-3km_restart_test_velo-fo_advec-fct_calving-von_mises_stress_damage-threshold_faceMelting
Total runtime 04:46
PASS: All passed successfully!
```

2023-09-06 16:46 UTC, matthewhoffman approved these changes
The long-awaited for day is upon us!  Awesome work @trhille !

2023-09-06 16:46 UTC, merged