Cshafer/hydro stats
MALI-Dev/E3SM pull request #82
Opened 2023-07-07 20:40 UTC by cshafer

This PR request includes updates to the global stats and regional stats to include new subglacial hydrology analysis members that were previously absent from `../analysis_members/mpas_li_<global or regional>_stats.F` and their associated registry files. The motivation behind this was to sidestep creating python scripts to evaluate these stats and to just include them in the main script - this would make it easier to evaluate the subglacial hydrology system, especially in confirming that the Antarctic-wide subglacial discharge map I'm generating (for my summer project) is accurate. 

The new analysis members so far include:
`totalSubglacialWaterVolume`
`totalLakeVolume`
`totalLakeArea`
`totalBasalMeltInput`
`totalExternalWaterInput`
`totalChannelMelt`
`totalGLMeltFlux`
`totalTerrestrialMeltFlux`
`totalChannelGLMeltFlux`
`totalChannelTerrestrialMeltFlux`
`totalFlotationFraction`
`avgFlotationFraction`

2023-07-10 17:28 UTC, matthewhoffman requested changes
@cshafer , this is a fantastic and long overdue addition to the subglacial hydrology model!  With one small exception, the calculations all look correct, so don't be scared by my many comments on variable names.  As we discussed, the plan is to not have you spend your time on PR revisions so that you can focus on your simulations, but if you prefer to do any additional work on the changes, let me know.

2023-07-10 17:28 UTC, matthewhoffman commented on components/mpas-albany-landice/src/analysis_members/mpas_li_global_stats.F
> +                blockSumFlotationFraction = blockSumFlotationFraction + ( waterPressure(iCell) / rhow / gravity / thickness(iCell) ) * areaCell(iCell)
This should use ice density:
```suggestion
                blockSumFlotationFraction = blockSumFlotationFraction + ( waterPressure(iCell) / rhoi / gravity / thickness(iCell) ) * areaCell(iCell)
```

2024-02-17 20:15 UTC, matthewhoffman approved these changes
# Testing
`full_integration` suite passes.  
I confirmed that when hydro model is on, the new global stats get written to the globalStats file and have reasonable values.

2024-02-17 20:18 UTC, merged

2024-02-20 02:30 UTC, cshafer commented
Woohoo!