Implement Runge-Kutta time integration
MALI-Dev/E3SM pull request #86
Opened 2023-08-31 18:02 UTC by trhille

This merge adds Runge-Kutta time integration to MALI, which is likely necessary when using higher-order advection. Currently, Runge-Kutta integration is used for damage evolution and thickness and tracer advection. Note that there is a slight change in the order of operations, as we have to move the subglacial hydrology step before the geometry update to allow multiple velocity solves during the Runge-Kutta integration.

2023-08-31 18:05 UTC, trhille commented
@matthewhoffman, I expect that this will require significant refactoring for flexibility, but I think having the in-progress PR open now will be useful for discussion and testing. Note that only the last six commits here are really relevant, as the others are due to merging my FCT branch into this one. I can clean up that history once the FCT branch is merged into `MALI-Dev/develop`.

2023-09-04 18:12 UTC, trhille commented
As of 2cd9970, most `full_integration` tests pass validation and baseline comparison, with the exception of:
```
landice/greenland/sia_restart_test
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_greenland_sia_restart_test.log
  test runtime:        00:19
landice/greenland/sia_decomposition_test
  * step: 1proc_run
  * step: 8proc_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_greenland_sia_decomposition_test.log
  test runtime:        00:12
landice/greenland/fo_decomposition_test
  * step: 16proc_run
  * step: 32proc_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_greenland_fo_decomposition_test.log
  test runtime:        01:13
landice/greenland/fo_restart_test
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: FAIL
  see: case_outputs/landice_greenland_fo_restart_test.log
  test runtime:        00:56
landice/humboldt/mesh-3km_restart_test/velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     FAIL
  baseline comparison: FAIL
  see: case_outputs/landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting.log
  test runtime:        00:43
landice/humboldt/mesh-3km_restart_test/velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting
  * step: full_run
  * step: restart_run
  test execution:      SUCCESS
  test validation:     FAIL
  baseline comparison: FAIL
  see: case_outputs/landice_humboldt_mesh-3km_restart_test_velo-fo-depthInt_calving-von_mises_stress_damage-threshold_faceMelting.log
  test runtime:        00:22
```

2023-09-22 16:26 UTC, trhille commented
One outstanding issue: what do we do about calculating `fluxAcrossGroundingLine`?
https://github.com/trhille/E3SM/blob/implement_rk_time_integration/components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F#L630-L659

It seems like this should be moved to occur after the RK loop. This is also a first-order treatment. Is it possible to update it to higher order when using fct advection?

2023-09-25 17:14 UTC, trhille commented
Testing
-------
I ran the `landice/mesh_convergence/horizontal_advection` case (https://github.com/MPAS-Dev/compass/pull/690) with the following settings:
```
config_thickness_advection = 'fct'
config_tracer_advection = 'fct'
config_horiz_tracer_adv_order = 3
config_advection_coef_3rd_order = 1.0
config_time_integration = 'runge_kutta'
config_rk_order = 3
config_rk3_stages = 3
```
We get close-to-third-order convergence:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/3714eb27-aa3a-469b-9641-3d7b93889d15)

2023-09-26 02:51 UTC, trhille commented
I ran the grounded slab test case with pure third-order advection and a uniform SMB of 1 m/yr.
Plots below are difference between grounded mass change and SMB for each RK case.
Three-stage RK3:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/ad6c6989-d27d-44ea-b612-f761d4eba4da)
Four-stage RK3:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/dbadb9d1-f6d6-4d4b-9840-270d0cd63910)
RK2:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/2304c5bc-4a4e-4427-8ce2-bc49e4681cc5)


These were calculated changing one line in `plot_mass_balance.py`
```
# get fields and plot stuff
volGround = f.variables['groundedIceVolume'][:]
volGround = volGround * rhoi / 1.0e12
dvolGround = np.zeros(yr.shape)
dvolGround[1:] = (volGround[1:]-volGround[:-1]) / dyr[1:]
#ax.plot(yr, dvolGround, 'k', linewidth=3, label="grounded mass change")

SMBg = f.variables['totalGroundedSfcMassBal'][:] / 1.0e12
ax.plot(yr, dvolGround - SMBg, label="mass change minus grounded SMB")
```

2023-09-27 00:17 UTC, trhille commented
Tested mass conservation using both surface and basal mass balance. SMB treated same as above. For BMB, I set `basalHeatFlux = 1.0` everywhere and added:
```
    config_thermal_solver = 'temperature'
    config_thermal_calculate_bmb = .true.
```

Three-stage RK3:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/9ce4fd13-8b57-419a-88d3-ee699e23d89e)

2023-10-03 22:19 UTC, trhille commented
Results of slotted cylinder test base using `config_horiz_tracer_adv_order = 3; config_advection_coef_3rd_order = 0.5`:
CFL fraction 0.99: https://drive.google.com/file/d/1TdydxWOpMwf76sOhQrbiTp_rBluyuTlo/view?usp=sharing
CFL fraction 0.25: https://drive.google.com/file/d/1kLvIexVLpmyvIeD5ye_7ngktQlrJN2yV/view?usp=sharing

2023-10-04 17:28 UTC, trhille commented
Testing the calculation of `groundedToFloatingThickness` and `fluxAcrossGroundingLine` after the Runge-Kutta loop (introduced in [3ec981a](https://github.com/MALI-Dev/E3SM/pull/86/commits/3ec981a13da03e02b4c6b37e48f2e82791e86479)). Currently this will only be correct for fo thickness advection, as higher order grounding line flux (#94) is awaiting review. I compared a run on this branch using both the 4-stage RK3 and forward Euler integration with a run compiled at commit 6d0d57212ff182495b032cfe164c07227027e2f2 using forward Euler. Neither budget completely closes, likely due to the same issues we've been having with budgets for a long time (see #38 and (https://github.com/MALI-Dev/E3SM/issues/23))

Forward Euler (6d0d572):
<img width="602" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/9c4bdbb9-2731-417f-bbec-2b3aed060796">

Forward Euler (3ec981a):
<img width="596" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/9b572ad9-4c3e-4a91-a862-00639a90b811">

RK3 (3ec981a):
<img width="596" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/f2f62d51-9c93-4ec3-9561-1d2c815ca5e9">

fractional error is calculated as `(SMBg+BMBg-GLflux-GLMigrationflux - dvolGround)/dvolGround`

2023-10-09 23:42 UTC, trhille commented
Here are `full_integration` results as of https://github.com/MALI-Dev/E3SM/pull/86/commits/4005761ac44cb4977fb5eabc04b61aee94d03978:

Forward Euler: all tests pass execution and validation. 
RK2: All tests pass execution, three fail validation:

- landice_hydro_radial_restart_test. `waterThickness` and `waterPressure` L_inf norms of 1.5e-15 and 4.7e-10, respectively
- landice_dome_2000m_fo_decomposition_test. `thickness` L2 norm of 1.7e-11 and `normalVelocity` L_inf norm of 1.1e-18
- landice_dome_variable_resolution_fo_decomposition_test.  `normalVelocity` L1 and L2 norms of  8.8e-17  l2: 1.68e-18

3-stage RK3: All tests pass execution, one fails validation:

- landice_hydro_radial_restart_test. `waterThickness` and `waterPressure` L_inf norms of 1.7e-15 and 4.7e-10, respectively

4-stage RK3: All tests pass execution, one fails validation:

- landice_hydro_radial_restart_test. `waterThickness` and `waterPressure` L_inf norms of 1.3e-15 and 4.7e-10, respectively

2023-10-23 18:54 UTC, matthewhoffman commented
The small differences for the `landice_dome_2000m_fo_decomposition_test` and `landice_dome_variable_resolution_fo_decomposition_test` are no concern, and we can just loosen the tolerances for those tests by an order of magnitude.   Thanks for digging in to the hydro failures.  Those are perplexing given the hydro solver is not directly affected by the time-stepping method, and nothing outside the hydro model is evolving in these tests.  I'll look at the code to see if I have any ideas about what could be going on there.

2023-10-23 22:33 UTC, trhille commented
Running the hydro radial restart test on 1 processor instead of 4 allowed it to pass validation.

2023-10-26 22:36 UTC, matthewhoffman commented
@trhille , the level of documentation you've made in this PR is really great.  A few questions for you:
1. What are you currently thinking about the treatment of restore_calving in the RK loop?  Having velocity solved on an expanded ice extent in the case when we impose a fixed ice extent seems potentially problem-causing.  That said, I'd also be happy to leave that for a separate PR as the RK and FCT methods are not yet used in any production configurations.
2. Given the extensive reordering of operations relative to what we've done before, do you think FE should be reordered to match?  (Again that could be a separate PR, if we even want to go there.)  Similarly, what's the feasibility of handling FE as first-order RK and dropping the old time-stepping module entirely (or deprecating for a period before removal)?

2023-10-26 23:41 UTC, matthewhoffman requested changes
@trhille , as monumental as this PR is, the implementation seems fairly straightforward, and I only have minor comments/requests.  The big work is probably in evaluating and blessing the changes to all the compass test cases.  Have you looked at baseline comparisons for Forward Euler yet?  I wonder how gruesome it is.  Given this PR is primarily bringing in new functionality that is not currently in production runs, and you've demonstrated that functionality is working as expected, at least to our current expectations, if the changes from baseline tests with FE make sense and are palatable, I don't see any obstructions to getting this merged in the next week or so.

Regarding the hydro_radial restart weirdness, I'm not entirely opposed to merging this without resolving that, but maybe after having looked this over carefully I'll have other ideas about what to look into.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         config_rk_order = 1
I don't see why this is needed as currently implemented and I'd rather not change config options, even if they are irrelevant based on other options.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      rkSSPweights(:) = 1.0_RKIND ! updated for each case below
Is 1.0 a good initialization value?  Or would some garbage value like -9999 be more likely to reveal if a weight gets used when it shouldn't?

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         err = 1
should we `return` here after the message?

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +                        waterFrac(k,iCell) = ( rkSSPweights(rkStage) * waterFracPrev(k,iCell) * layerThicknessPrev(k,iCell) + &
I forget - are we calculating this at all when using the `temperature` option?  I guess if it's all zeros it doesn't hurt to do this.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         call li_calculate_mask(meshPool, velocityPool, geometryPool, err_tmp)
Are these lines of mask operations needed here?  They don't hurt, but they seem sort of random.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +            call li_calculate_layerThickness(meshPool, thickness, layerThickness)
Why is this added here?

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      basalMassBalAccum(:) = 0.0_RKIND
I'm not sure where to put this comment, but this seems as good a place as any.  The enthalpy solver includes the possibility of internal melt in excess of a water fraction limit that drains out and is instantaneously added to basal mass balance.  I believe that is added to `basalMassBal`.  So I don't think there's any problem in that it will automatically be included in the RK application of BMB - RK doesn't need to know where that ablation came from and will handle turning it into `basalMassBalApplied`.  But I wanted to mention it in case there is any complication I'm not thinking of with that.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         call li_velocity_solve(domain, solveVelo=.true., err=err_tmp)
It's nice that modified the routine that zaps ice about a speed threshold into just limiting its velocity.  Otherwise we'd have to deal with the possibility of the velocity solver changing the geometry a la calving.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +               fluxAcrossGroundingLineOnCells(theGroundedCell) = fluxAcrossGroundingLineOnCells(theGroundedCell) + &
This calculation was previously happening somewhere else, but I don't remember where.  I don't see it removed from elsewhere in the PR diff, but presumably we don't want it being calculated twice.

2023-10-26 23:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      call li_velocity_solve(domain, solveVelo=.false., err=err_tmp)
Did we decide we definitely want an extra velo solve for consistent calving?  Regardless, can you update the PR description to discuss this extra operation/cost?

2023-10-27 01:30 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +                            possible_values="1, 2, 3"
RK1 is identical to FE. What about dropping support for `config_rk_order = 1` to avoid any possible confusion while keeping backwards compatibility?

2023-10-27 01:32 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         config_rk_order = 1
Oh yeah that's a mistake and not necessary or helpful.

2023-10-27 01:35 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +            call li_calculate_layerThickness(meshPool, thickness, layerThickness)
See commit message for 95238409b40e396eb2af26765a322f3dd82dcf00.

2023-10-27 01:37 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      call li_velocity_solve(domain, solveVelo=.false., err=err_tmp)
We did not make a decision, but we need to at some point.

2023-10-27 01:39 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +               fluxAcrossGroundingLineOnCells(theGroundedCell) = fluxAcrossGroundingLineOnCells(theGroundedCell) + &
Good catch. This is still being calculated in `li_advection_thickness_tracers`. I don't remember if that's intentional or not, but I'll look into it.

2023-10-27 01:44 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         call li_calculate_mask(meshPool, velocityPool, geometryPool, err_tmp)
I think it's necessary after updating thickness above, but you're right that it feels out of place where it is. I'll move it.

2023-10-27 01:46 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +                        waterFrac(k,iCell) = ( rkSSPweights(rkStage) * waterFracPrev(k,iCell) * layerThicknessPrev(k,iCell) + &
I believe it should be all zeroes if using `temperature` solver. I implemented it this way to avoid more if-statements.

2023-10-27 01:52 UTC, trhille commented
Thanks for the review, @matthewhoffman! I'm glad it was more straightforward to review than we probably both anticipated.

> Regarding the hydro_radial restart weirdness, I'm not entirely opposed to merging this without resolving that, but maybe after having looked this over carefully I'll have other ideas about what to look into.
It's definitely tempting to merge without fixing the hydro_radial restart issue, but it also makes me nervous because then we have a baseline that we know to be incorrect for that test.

2023-10-27 03:40 UTC, matthewhoffman commented
@trhille , do you have any results on relative computational cost between these schemes?  (e.g. compass timers)  I don't want a whole performance study for this PR, but a rough sense of the impact would be good to know.  (Though that may change depending on how we handle the 'extra' calving velocity solve issue.)

2023-10-27 15:54 UTC, trhille commented
Compass runtimes on Chicoma:
Forward Euler: 16:26
RK2: 18:40
3-stage RK3: 20:25
4-stage RK3: 21:31

Note that `landice_hydro_radial_decomposition_test` now takes about 6.5 minutes on Chicoma, for some reason.

2023-10-30 14:44 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      allocate(waterFracPrev(nVertLevels, nCells+1))
Addressed in dd444ca65ac03c7f94d8e8aef5cecb113884e070.

2023-10-30 14:44 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         config_rk_order = 1
Addressed in dd444ca65ac03c7f94d8e8aef5cecb113884e070.

2023-10-30 14:44 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         err = 1
Addressed in dd444ca65ac03c7f94d8e8aef5cecb113884e070.

2023-10-30 14:44 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +         call li_calculate_mask(meshPool, velocityPool, geometryPool, err_tmp)
Addressed in dd444ca65ac03c7f94d8e8aef5cecb113884e070.

2023-10-30 15:26 UTC, trhille commented
>     1. What are you currently thinking about the treatment of restore_calving in the RK loop?  Having velocity solved on an expanded ice extent in the case when we impose a fixed ice extent seems potentially problem-causing.  That said, I'd also be happy to leave that for a separate PR as the RK and FCT methods are not yet used in any production configurations.

@matthewhoffman, sorry I somehow missed this question. This is a good point. We could include a call to `li_restore_calving_front` within the RK loop before the velocity solve, but deal with any other calving outside of the RK loop. Or we could accept that for purposes of RK integration the calving front may be allowed to advance beyond the initial extent with the knowledge that it will be dealt with before the end of the time step. If we decide to add yet another velocity solve after calving, that might be the way to go. But as you say, this might be better as the subject of another PR.

2023-10-30 17:55 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      rkSSPweights(:) = 1.0_RKIND ! updated for each case below
Addressed in https://github.com/MALI-Dev/E3SM/pull/86/commits/8d5f28e6dbdaa6d685e79ab0e6287224562f03c9.

2023-10-30 18:58 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +                            possible_values="1, 2, 3"
Removed support for `config_rk_order = 1` in  ada4117017ee3f905891ad107112e2f9ca3eca7c.

2023-11-06 19:01 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +      basalMassBalAccum(:) = 0.0_RKIND
In this case, `drainedInternalMeltRate` is calculated in `li_thermal` prior to the RK loop, and is added to `basalMassBal` at each stage. So I think you're correct that this is taken care of automatically and we don't need to track `drainedInternalMeltRate`  through each stage.

2023-11-06 20:27 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_time_integration_fe_rk.F
> +               fluxAcrossGroundingLineOnCells(theGroundedCell) = fluxAcrossGroundingLineOnCells(theGroundedCell) + &
Addressed in 51802e1bca96f70da0a72ab6786116b88dfa9c67

2023-11-08 21:05 UTC, trhille commented
Testing mesh convergence in a simplified test case with calving at https://github.com/MALI-Dev/E3SM/pull/86/commits/e2a2f0b9389ed3810d0332664a25596a9e316441. I used the `circular_shelf` COMPASS test to create four shelves with 40 km radius at 10km, 5km, 2.5km, and 1.25km resolution. I gave them very small, radially symmetric velocities:
`ncap2 -s uReconstructX = xCell / (1.0e5* 3.154e7); uReconstructY = yCell / (1.0e5 * 3.154e7) landice_grid.nc`

I then ran these forward for 10 years using the following relevant namelist settings, designed to result in a shelf of 30 km radius at the end of the run:
```
    config_velocity_solver = 'none'

    config_thickness_advection = 'fct'
    config_tracer_advection = 'none'
    config_horiz_tracer_adv_order = 3
    config_advection_coef_3rd_order = 1.0

    config_calving = 'specified_calving_velocity'
    config_calving_specified_source = 'const'
    config_calving_velocity_const = 3.17415e-5 ! 1km/yr

    config_rk_order = 3
    config_rk3_stages = 3
    config_adaptive_timestep = .true.
    config_min_adaptive_timestep = 0.0
    config_max_adaptive_timestep = 3.15e9
    config_adaptive_timestep_CFL_fraction = 0.25
    config_adaptive_timestep_calvingCFL_fraction = 0.25
```
I then created the 30km-radius shelves at the same resolutions and used these as the "true" solution for each run.
I used both area and volume error metrics, which give slightly different convergence orders:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/dc08ecf5-ec01-4dad-8b1f-07332d2a844b)

2023-11-09 20:34 UTC, trhille commented
`full_integration` results at https://github.com/MALI-Dev/E3SM/pull/86/commits/e2a2f0b9389ed3810d0332664a25596a9e316441:
Forward Euler: all tests pass validation and baseline comparison. Run time on Chicoma = 15:56
RK2: Run time on Chicoma = 18:16
Tests failing validation:

- `landice/hydro_radial/restart_test`
- `landice/humboldt/mesh-3km_restart_test/velo-none_calving-none_subglacialhydro`
- `landice/dome/2000m/fo_decomposition_test`
- `landice/dome/variable_resolution/fo_decomposition_test`

3-stage RK3: Run time on Chicoma = 20:00
Tests failing validation:

- `landice/hydro_radial/restart_test`
- `landice/humboldt/mesh-3km_restart_test/velo-none_calving-none_subglacialhydro`

4-stage RK3: Run time on Chicoma = 21:07
Tests failing validation:

- `landice/hydro_radial/restart_test`
- `landice/humboldt/mesh-3km_restart_test/velo-none_calving-none_subglacialhydro`

All tests using Runge-Kutta time integration fail baseline comparison except for `landice_circular_shelf_decomposition_test`, which has no time evolution.
This includes failure of baseline comparison for the `landice/enthalpy_benchmark/A` test, which is somewhat confusing because there is no geometry evolution. However, the errors are small enough that they may stem from round-off error in the reconstruction of the forcing term in the RK loop.
Here are the error norms from the last time step of the 3-stage RK3 compared the the forward-Euler baseline:
Temperature: `149: l1: 5.80939740757458e-10  l2: 4.31429191711591e-11  linf: 3.58113538823090e-12`
basalWaterThickness: `79:  l1: 3.68393475058681e-07  l2: 1.84196737529341e-07  linf: 9.20983687646704e-08`
groundedBasalMassBal: `79:  l1: 6.14892980147419e-20  l2: 3.07446490073709e-20  linf: 1.53723245036855e-20`

2023-11-10 02:34 UTC, trhille commented
Mesh Convergence Testing
---------------------------
Testing mesh convergence using Matt's COMPASS branch at https://github.com/matthewhoffman/compass/commit/080d1f0d838f0b10229a5f0be100d83de649c53c, using 1, 2 ,4, and 8km meshes. I used the following relevant namelist settings:
```
    config_thickness_advection = 'fct'
    config_tracer_advection = 'fct'
    config_horiz_tracer_adv_order = 3
    config_advection_coef_3rd_order = 1.0

    config_time_integration = 'runge_kutta'
    config_rk_order = 3
    config_rk3_stages = 3
```
`horizontal_advection` tests give close to third-order convergence:
<img width="571" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/8eadcace-653b-4c70-93d3-5f02ae5badb5">
<img width="580" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/af17a879-91b8-45fa-a23f-060eaaa55b3e">

Meanwhile, the Halfar dome test gives first order convergence. It's unclear if that is because of the SIA velocity, the first-order treatment at the ice margins, or something else. Running for 1000 years instead of 200 years did not improve convergence order.
<img width="571" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/cd20ca74-ce35-432b-99fd-eeb52585693e">

2023-11-10 04:19 UTC, trhille commented
Even more testing
------------------
I ran the `fct_integration` suite  (https://github.com/trhille/compass/commit/c884eaf5d3703a6e11e0d3216f09c3216f657a8a) for the following cases: 2nd-order advection with RK2, 3rd-order FCT (beta = 0.5) with 3-stage RK3, and 3rd-order FCT (beta = 0.5) with 4-stage RK3. All tests passed validation, except for the 2nd-order `landice_dome_variable_resolution_fo_fct_decomposition_test`, which had the following error norms:
`thickness`: `2:  l1: 1.54766681241536e-11  l2: 1.69923778717874e-12  linf: 4.54747350886464e-13`
`normalVelocity`: `1:  l1: 8.22396491678941e-17  l2: 1.52703232416953e-18  linf: 9.42324153820409e-20`
which are small enough to be ignored.

2023-11-10 17:34 UTC, trhille commented
Bonus convergence testing
---------------------------
2nd order advection, RK2:
![image](https://github.com/MALI-Dev/E3SM/assets/17446278/0ff058ad-5169-4289-8c1a-277b3d48821c)
3rd order advection, 4-stage RK3: still running
3rd order FCT with various coefficients, 3-stage RK3: still running

2023-11-11 02:41 UTC, matthewhoffman approved these changes
@trhille , this is amazing work!  And the testing... I can't find anything to nitpick about and will merge this now.  As we discussed, there are some subtleties with the RK treatment we don't fully understand, but all the meaningful configurations we want to support look great and the existing Forward Euler behavior is bit-for-bit.  Thanks for documenting all the testing results.

2023-11-11 20:54 UTC, merged