Calculate higher-order flux across grounding line
MALI-Dev/E3SM pull request #94
Opened 2023-10-04 04:19 UTC by trhille

When using higher-order thickness advection, calculate higher-order flux across grounding line.

2023-10-04 12:43 UTC, trhille commented
Testing
-------
I ran an fo and a 3rd-order order fct (beta = 0.25) thickness advection case on the `MISMIP_2km_20220502.nc` with velocity solver turned off. Grounding line fluxes look similar, although fct is noisier. Blue is fct, orange is fo:
<img width="406" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/4b7d1b2d-6903-460d-afcc-984b29b7cb73">

2023-10-04 15:12 UTC, matthewhoffman commented
Regarding "FCT grounded mass budget closes" comment, I assume then that it did not close without this change?

2023-10-04 16:18 UTC, trhille commented
> Regarding "FCT grounded mass budget closes" comment, I assume then that it did not close without this change?

Okay, it looks like it's more complicated than this. The budget actually doesn't _quite_ close with this change. It also doesn't close before this change, and it doesn't even close completely when using fo advection. So I think this goes back to the issue that we've been having with budgets in general.

2023-10-04 18:17 UTC, trhille commented
Fractional error in the mass budget relative to total change using fct thickness adveciton.
[4eb8b82](https://github.com/MALI-Dev/E3SM/pull/94/commits/4eb8b8286633ea6f5bcbfe9d5cd88effac833bf4)
<img width="587" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/1ad40881-9ba9-4ba4-9e47-e70e6c69a2ca">

[f5d2e27](https://github.com/MALI-Dev/E3SM/commit/f5d2e2728ad094e14e45ede8a007f997ccda6749) (MALI-Dev/develop)
<img width="592" alt="image" src="https://github.com/MALI-Dev/E3SM/assets/17446278/e3a4e050-7de4-4eb0-af5c-22645329d8a8">

So, while neither budget totally closes, this is a great improvement over using first-order grounding line flux when using fct thickness advection.

2023-10-04 18:41 UTC, matthewhoffman requested changes
@trhille , thanks for taking care of this addition.  I made two minor comments that you can take or leave.  I marked this as 'request changes' but I'm happy to proceed as-is if you prefer not to make either change.

2023-10-04 18:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                     thicknessFluxEdge = layerNormalVelocity(k,iEdge) * dvEdge(iEdge) * layerThicknessEdge(k,iEdge)
How about using the new variable here so that if we ever want to use it in output we have that field available regardless of advection scheme?
```suggestion
                     layerThicknessEdgeFlux(k,iEdge) = layerNormalVelocity(k,iEdge) * dvEdge(iEdge) * layerThicknessEdge(k,iEdge)
```
(and corresponding adjustment to 652)

2023-10-04 18:41 UTC, matthewhoffman commented on components/mpas-albany-landice/src/Registry.xml
> +		<var name="layerThicknessEdgeFlux" type="real" dimensions="nVertLevels nEdges Time" units="m^2 s^{-1}"
nitpicky question - could/should this be called just `layerEdgeFlux`?  I don't feel strongly about this and it's not important enough to change everywhere unless you like the idea.

2023-10-04 18:53 UTC, trhille commented on components/mpas-albany-landice/src/Registry.xml
> +		<var name="layerThicknessEdgeFlux" type="real" dimensions="nVertLevels nEdges Time" units="m^2 s^{-1}"
MPAS-Ocean calls it `normalThicknessFlux`, so I left "thickness" in the name. I could go either way.

2023-10-04 20:40 UTC, trhille commented
All `full_integration` tests passed validation and baseline comparison.

2023-10-04 21:25 UTC, trhille commented
All `fct_integration` tests passed validation and baseline comparison.

2023-10-09 18:11 UTC, trhille commented on components/mpas-albany-landice/src/mode_forward/mpas_li_advection.F
> +                     thicknessFluxEdge = layerNormalVelocity(k,iEdge) * dvEdge(iEdge) * layerThicknessEdge(k,iEdge)
Addressed in [8be7fbb](https://github.com/MALI-Dev/E3SM/pull/94/commits/8be7fbbe2bdffc2cff301fa69ec0a0417696ab87)

2023-10-09 21:53 UTC, matthewhoffman approved these changes
@trhille , thanks for generalizing the calculation.  I'm happy to proceed with merging this.

2023-10-09 22:36 UTC, merged